// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddBeginRequest struct {
	Label string `json:"label"` // 硬件设备备注名 (e.g. YubiKey 5C, MacBook TouchID)
}

type AddBeginResponse struct {
	Options string `json:"options"` // 序列化后的 PublicKeyCredentialCreationOptions
}

type AddFinishRequest struct {
	Response string `json:"response"` // 浏览器返回的 PublicKeyCredential
}

type AddFinishResponse struct {
	Success bool `json:"success"`
}

type CredentialItem struct {
	Id         int64  `json:"id"`
	Label      string `json:"label"`
	Aaguid     string `json:"aaguid"`
	LastUsedAt int64  `json:"lastUsedAt"`
	CreatedAt  int64  `json:"createdAt"`
}

type ListResponse struct {
	List []CredentialItem `json:"list"`
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type SystemInfoReq struct {
}

type SystemInfoResp struct {
	Version    string `json:"version"`     // 版本号
	BuildTime  string `json:"build_time"`  // 构建时间
	CommitHash string `json:"commit_hash"` // 提交哈希
}

type VerifyBeginRequest struct {
	Action string `json:"action,optional"` // 触发验证的行为类型 (e.g. "2fa", "withdraw", "update_risk")
}

type VerifyBeginResponse struct {
	Options string `json:"options"` // 序列化后的 PublicKeyCredentialRequestOptions
}

type VerifyFinishRequest struct {
	Response string `json:"response"` // 浏览器返回的 AuthenticatorAssertionResponse
}

type VerifyFinishResponse struct {
	VerifiedToken string `json:"verifiedToken"` // 验证成功后的短期令牌，用于执行受保护的操作
}
