// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	passkey "github.com/iluyuns/alpha-trade/internal/handler/passkey"
	system "github.com/iluyuns/alpha-trade/internal/handler/system"
	"github.com/iluyuns/alpha-trade/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 绑定新的 Passkey (需已登录)
					Method:  http.MethodPost,
					Path:    "/add/begin",
					Handler: passkey.AddBeginHandler(serverCtx),
				},
				{
					// 完成 Passkey 绑定
					Method:  http.MethodPost,
					Path:    "/add/finish",
					Handler: passkey.AddFinishHandler(serverCtx),
				},
				{
					// 获取已绑定的 Passkey 列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: passkey.ListHandler(serverCtx),
				},
				{
					// 移除指定的 Passkey
					Method:  http.MethodDelete,
					Path:    "/remove",
					Handler: passkey.RemoveHandler(serverCtx),
				},
				{
					// 发起 Passkey 挑战 (2FA/提级认证)
					Method:  http.MethodPost,
					Path:    "/verify/begin",
					Handler: passkey.VerifyBeginHandler(serverCtx),
				},
				{
					// 提交 Passkey 验证结果
					Method:  http.MethodPost,
					Path:    "/verify/finish",
					Handler: passkey.VerifyFinishHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/passkey"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.Passkey},
			[]rest.Route{
				{
					// Get System Info
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: system.SystemInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)
}
