// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "github.com/iluyuns/alpha-trade/internal/handler/auth"
	authpasskey "github.com/iluyuns/alpha-trade/internal/handler/auth/passkey"
	dashboard "github.com/iluyuns/alpha-trade/internal/handler/dashboard"
	notifications "github.com/iluyuns/alpha-trade/internal/handler/notifications"
	system "github.com/iluyuns/alpha-trade/internal/handler/system"
	trading "github.com/iluyuns/alpha-trade/internal/handler/trading"
	"github.com/iluyuns/alpha-trade/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 基础登录 (密码)
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.AuthLoginHandler(serverCtx),
			},
			{
				// 退出登录
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.AuthLogoutHandler(serverCtx),
			},
			{
				// OAuth2 回调 (由第三方平台跳回)
				Method:  http.MethodGet,
				Path:    "/oauth2/callback",
				Handler: auth.AuthOAuth2CallbackHandler(serverCtx),
			},
			{
				// 发起 OAuth2 登录 (重定向到 Google/GitHub)
				Method:  http.MethodGet,
				Path:    "/oauth2/init",
				Handler: auth.AuthOAuth2InitHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 绑定新的 Passkey (需已登录)
					Method:  http.MethodPost,
					Path:    "/add/begin",
					Handler: authpasskey.PasskeyAddBeginHandler(serverCtx),
				},
				{
					// 完成 Passkey 绑定
					Method:  http.MethodPost,
					Path:    "/add/finish",
					Handler: authpasskey.PasskeyAddFinishHandler(serverCtx),
				},
				{
					// 获取已绑定的 Passkey 列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: authpasskey.PasskeyListHandler(serverCtx),
				},
				{
					// 移除指定的 Passkey
					Method:  http.MethodDelete,
					Path:    "/remove",
					Handler: authpasskey.PasskeyRemoveHandler(serverCtx),
				},
				{
					// 发起 Passkey 挑战 (2FA/提级认证)
					Method:  http.MethodPost,
					Path:    "/verify/begin",
					Handler: authpasskey.PasskeyVerifyBeginHandler(serverCtx),
				},
				{
					// 提交 Passkey 验证结果
					Method:  http.MethodPost,
					Path:    "/verify/finish",
					Handler: authpasskey.PasskeyVerifyFinishHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/auth/passkey"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.MFA},
			[]rest.Route{
				{
					// 获取 Dashboard 数据
					Method:  http.MethodGet,
					Path:    "/",
					Handler: dashboard.DashboardHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/dashboard"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.MFA},
			[]rest.Route{
				{
					// 订阅 Web Push 通知
					Method:  http.MethodPost,
					Path:    "/subscribe",
					Handler: notifications.SubscribeHandler(serverCtx),
				},
				{
					// 发送测试通知
					Method:  http.MethodPost,
					Path:    "/test",
					Handler: notifications.SendTestHandler(serverCtx),
				},
				{
					// 取消订阅 Web Push 通知
					Method:  http.MethodPost,
					Path:    "/unsubscribe",
					Handler: notifications.UnsubscribeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/notifications"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.MFA},
			[]rest.Route{
				{
					// Get System Info
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: system.SystemInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth, serverCtx.MFA},
			[]rest.Route{
				{
					// 启动交易循环
					Method:  http.MethodPost,
					Path:    "/start",
					Handler: trading.TradingStartHandler(serverCtx),
				},
				{
					// 查询交易状态
					Method:  http.MethodGet,
					Path:    "/status",
					Handler: trading.TradingStatusHandler(serverCtx),
				},
				{
					// 停止交易循环
					Method:  http.MethodPost,
					Path:    "/stop",
					Handler: trading.TradingStopHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/trading"),
	)
}
