// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:07Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	assetSnapshotsFieldNames        = builder.RawFieldNames(&AssetSnapshots{}, true)
	assetSnapshotsRows              = strings.Join(assetSnapshotsFieldNames, ",")
	assetSnapshotsRowsExpectAutoSet = strings.Join(stringx.Remove(assetSnapshotsFieldNames, "id"), ",")
)

type (
	assetSnapshotsModel interface {
		Insert(ctx context.Context, data *AssetSnapshots) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *AssetSnapshots) (*AssetSnapshots, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*AssetSnapshots) ([]*AssetSnapshots, error)
		FindOne(ctx context.Context, id int64) (*AssetSnapshots, error)
		Update(ctx context.Context, data *AssetSnapshots) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAssetSnapshotsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AssetSnapshots struct {
		Id               int64     `db:"id"`                // 流水 ID
		Exchange         string    `db:"exchange"`          // 交易所类型
		TotalBalance     float64   `db:"total_balance"`     // 总权益估值 (USDT)
		AvailableBalance float64   `db:"available_balance"` // 可用余额 (USDT)
		FrozenBalance    float64   `db:"frozen_balance"`    // 冻结金额 (USDT)
		SnapshotTime     time.Time `db:"snapshot_time"`     // 快照生成时间
	}
)

func newAssetSnapshotsModel(conn sqlx.SqlConn) *defaultAssetSnapshotsModel {
	return &defaultAssetSnapshotsModel{
		conn:  conn,
		table: "\"public\".\"asset_snapshots\"",
	}
}

func (m *defaultAssetSnapshotsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAssetSnapshotsModel) FindOne(ctx context.Context, id int64) (*AssetSnapshots, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", assetSnapshotsRows, m.table)
	var resp AssetSnapshots
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAssetSnapshotsModel) Insert(ctx context.Context, data *AssetSnapshots) (sql.Result, error) {
	builder := m.insertBuilder().Columns(assetSnapshotsRowsExpectAutoSet).Values(data.Exchange, data.TotalBalance, data.AvailableBalance, data.FrozenBalance, data.SnapshotTime)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultAssetSnapshotsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*AssetSnapshots) ([]*AssetSnapshots, error) {
	builder := m.insertBuilder().Columns(assetSnapshotsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.Exchange, data.TotalBalance, data.AvailableBalance, data.FrozenBalance, data.SnapshotTime)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultAssetSnapshotsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *AssetSnapshots) (*AssetSnapshots, error) {
	builder := m.insertBuilder().Columns(assetSnapshotsRowsExpectAutoSet).Values(data.Exchange, data.TotalBalance, data.AvailableBalance, data.FrozenBalance, data.SnapshotTime)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultAssetSnapshotsModel) Update(ctx context.Context, newData *AssetSnapshots) error {
	builder := m.updateBuilder()
	builder = builder.Set("exchange", newData.Exchange)
	builder = builder.Set("total_balance", newData.TotalBalance)
	builder = builder.Set("available_balance", newData.AvailableBalance)
	builder = builder.Set("frozen_balance", newData.FrozenBalance)
	builder = builder.Set("snapshot_time", newData.SnapshotTime)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultAssetSnapshotsModel) tableName() string {
	return m.table
}

func (m *defaultAssetSnapshotsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultAssetSnapshotsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAssetSnapshotsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAssetSnapshotsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAssetSnapshotsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAssetSnapshotsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultAssetSnapshotsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*AssetSnapshots, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AssetSnapshots
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultAssetSnapshotsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*AssetSnapshots, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp AssetSnapshots
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultAssetSnapshotsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultAssetSnapshotsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*AssetSnapshots, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AssetSnapshots
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultAssetSnapshotsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultAssetSnapshotsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultAssetSnapshotsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(assetSnapshotsFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultAssetSnapshotsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultAssetSnapshotsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*AssetSnapshots, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AssetSnapshots
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultAssetSnapshotsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*AssetSnapshots, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AssetSnapshots
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
