// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:07Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	auditLogsFieldNames        = builder.RawFieldNames(&AuditLogs{}, true)
	auditLogsRows              = strings.Join(auditLogsFieldNames, ",")
	auditLogsRowsExpectAutoSet = strings.Join(stringx.Remove(auditLogsFieldNames, "id"), ",")
)

type (
	auditLogsModel interface {
		Insert(ctx context.Context, data *AuditLogs) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *AuditLogs) (*AuditLogs, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*AuditLogs) ([]*AuditLogs, error)
		FindOne(ctx context.Context, id int64) (*AuditLogs, error)
		Update(ctx context.Context, data *AuditLogs) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuditLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuditLogs struct {
		Id         int64     `db:"id"`          // 日志自增 ID
		UserId     int64     `db:"user_id"`     // 操作执行人 ID
		IpAddress  string    `db:"ip_address"`  // 操作者 IP 地址
		Action     string    `db:"action"`      // 行为类型 [ENUM: KILL_SWITCH, UPDATE_RISK, API_KEY_ADD, STRATEGY_START]
		TargetType string    `db:"target_type"` // 操作对象类别 [ENUM: ACCOUNT, RISK_CONFIG, STRATEGY, USER]
		TargetId   string    `db:"target_id"`   // 操作对象 ID
		Changes    string    `db:"changes"`     // 变更 Diff 内容 [JSON: old, new]
		IsVerified bool      `db:"is_verified"` // 是否通过了 Passkey 二次提级认证
		CreatedAt  time.Time `db:"created_at"`  // 审计记录时间
	}
)

func newAuditLogsModel(conn sqlx.SqlConn) *defaultAuditLogsModel {
	return &defaultAuditLogsModel{
		conn:  conn,
		table: "\"public\".\"audit_logs\"",
	}
}

func (m *defaultAuditLogsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuditLogsModel) FindOne(ctx context.Context, id int64) (*AuditLogs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", auditLogsRows, m.table)
	var resp AuditLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultAuditLogsModel) Insert(ctx context.Context, data *AuditLogs) (sql.Result, error) {
	builder := m.insertBuilder().Columns(auditLogsRowsExpectAutoSet).Values(data.UserId, data.IpAddress, data.Action, data.TargetType, data.TargetId, data.Changes, data.IsVerified, data.CreatedAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultAuditLogsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*AuditLogs) ([]*AuditLogs, error) {
	builder := m.insertBuilder().Columns(auditLogsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.UserId, data.IpAddress, data.Action, data.TargetType, data.TargetId, data.Changes, data.IsVerified, data.CreatedAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultAuditLogsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *AuditLogs) (*AuditLogs, error) {
	builder := m.insertBuilder().Columns(auditLogsRowsExpectAutoSet).Values(data.UserId, data.IpAddress, data.Action, data.TargetType, data.TargetId, data.Changes, data.IsVerified, data.CreatedAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultAuditLogsModel) Update(ctx context.Context, newData *AuditLogs) error {
	builder := m.updateBuilder()
	builder = builder.Set("user_id", newData.UserId)
	builder = builder.Set("ip_address", newData.IpAddress)
	builder = builder.Set("action", newData.Action)
	builder = builder.Set("target_type", newData.TargetType)
	builder = builder.Set("target_id", newData.TargetId)
	builder = builder.Set("changes", newData.Changes)
	builder = builder.Set("is_verified", newData.IsVerified)
	builder = builder.Set("created_at", newData.CreatedAt)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultAuditLogsModel) tableName() string {
	return m.table
}

func (m *defaultAuditLogsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultAuditLogsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAuditLogsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAuditLogsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAuditLogsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultAuditLogsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultAuditLogsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*AuditLogs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AuditLogs
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultAuditLogsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*AuditLogs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp AuditLogs
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultAuditLogsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultAuditLogsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*AuditLogs, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AuditLogs
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultAuditLogsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultAuditLogsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultAuditLogsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(auditLogsFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultAuditLogsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultAuditLogsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*AuditLogs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AuditLogs
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultAuditLogsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*AuditLogs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*AuditLogs
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
