// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:06Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	exchangeAccountsFieldNames        = builder.RawFieldNames(&ExchangeAccounts{}, true)
	exchangeAccountsRows              = strings.Join(exchangeAccountsFieldNames, ",")
	exchangeAccountsRowsExpectAutoSet = strings.Join(stringx.Remove(exchangeAccountsFieldNames, "id"), ",")
)

type (
	exchangeAccountsModel interface {
		Insert(ctx context.Context, data *ExchangeAccounts) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *ExchangeAccounts) (*ExchangeAccounts, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*ExchangeAccounts) ([]*ExchangeAccounts, error)
		FindOne(ctx context.Context, id int64) (*ExchangeAccounts, error)
		Update(ctx context.Context, data *ExchangeAccounts) error
		Delete(ctx context.Context, id int64) error
	}

	defaultExchangeAccountsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ExchangeAccounts struct {
		Id                  int64     `db:"id"`                   // 账户自增 ID
		UserId              int64     `db:"user_id"`              // 所属系统用户 ID
		Label               string    `db:"label"`                // 账户备注名称 (e.g., Binance_Sub_01)
		Exchange            string    `db:"exchange"`             // 交易所类型 [ENUM: BINANCE, OKX]
		ApiKey              string    `db:"api_key"`              // 交易所 API Key
		EncryptedApiSecret  string    `db:"encrypted_api_secret"` // 加密后的 API Secret (AES-256-GCM)
		EncryptedPassphrase string    `db:"encrypted_passphrase"` // 加密后的 OKX Passphrase (仅 OKX 必填)
		Config              string    `db:"config"`               // 扩展配置 [JSON: ip_whitelist, is_master]
		IsActive            bool      `db:"is_active"`            // 账户启用状态
		CreatedAt           time.Time `db:"created_at"`           // 记录创建时间
		UpdatedAt           time.Time `db:"updated_at"`           // 最后更新时间
	}
)

func newExchangeAccountsModel(conn sqlx.SqlConn) *defaultExchangeAccountsModel {
	return &defaultExchangeAccountsModel{
		conn:  conn,
		table: "\"public\".\"exchange_accounts\"",
	}
}

func (m *defaultExchangeAccountsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultExchangeAccountsModel) FindOne(ctx context.Context, id int64) (*ExchangeAccounts, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", exchangeAccountsRows, m.table)
	var resp ExchangeAccounts
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultExchangeAccountsModel) Insert(ctx context.Context, data *ExchangeAccounts) (sql.Result, error) {
	builder := m.insertBuilder().Columns(exchangeAccountsRowsExpectAutoSet).Values(data.UserId, data.Label, data.Exchange, data.ApiKey, data.EncryptedApiSecret, data.EncryptedPassphrase, data.Config, data.IsActive, data.CreatedAt, data.UpdatedAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultExchangeAccountsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*ExchangeAccounts) ([]*ExchangeAccounts, error) {
	builder := m.insertBuilder().Columns(exchangeAccountsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.UserId, data.Label, data.Exchange, data.ApiKey, data.EncryptedApiSecret, data.EncryptedPassphrase, data.Config, data.IsActive, data.CreatedAt, data.UpdatedAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultExchangeAccountsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *ExchangeAccounts) (*ExchangeAccounts, error) {
	builder := m.insertBuilder().Columns(exchangeAccountsRowsExpectAutoSet).Values(data.UserId, data.Label, data.Exchange, data.ApiKey, data.EncryptedApiSecret, data.EncryptedPassphrase, data.Config, data.IsActive, data.CreatedAt, data.UpdatedAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultExchangeAccountsModel) Update(ctx context.Context, newData *ExchangeAccounts) error {
	builder := m.updateBuilder()
	builder = builder.Set("user_id", newData.UserId)
	builder = builder.Set("label", newData.Label)
	builder = builder.Set("exchange", newData.Exchange)
	builder = builder.Set("api_key", newData.ApiKey)
	builder = builder.Set("encrypted_api_secret", newData.EncryptedApiSecret)
	builder = builder.Set("encrypted_passphrase", newData.EncryptedPassphrase)
	builder = builder.Set("config", newData.Config)
	builder = builder.Set("is_active", newData.IsActive)
	builder = builder.Set("created_at", newData.CreatedAt)
	builder = builder.Set("updated_at", newData.UpdatedAt)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultExchangeAccountsModel) tableName() string {
	return m.table
}

func (m *defaultExchangeAccountsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultExchangeAccountsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExchangeAccountsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExchangeAccountsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExchangeAccountsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExchangeAccountsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultExchangeAccountsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*ExchangeAccounts, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*ExchangeAccounts
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultExchangeAccountsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*ExchangeAccounts, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp ExchangeAccounts
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultExchangeAccountsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultExchangeAccountsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*ExchangeAccounts, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*ExchangeAccounts
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultExchangeAccountsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultExchangeAccountsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultExchangeAccountsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(exchangeAccountsFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultExchangeAccountsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultExchangeAccountsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*ExchangeAccounts, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*ExchangeAccounts
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultExchangeAccountsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*ExchangeAccounts, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*ExchangeAccounts
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
