// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:07Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	executionsFieldNames        = builder.RawFieldNames(&Executions{}, true)
	executionsRows              = strings.Join(executionsFieldNames, ",")
	executionsRowsExpectAutoSet = strings.Join(stringx.Remove(executionsFieldNames, "id"), ",")
)

type (
	executionsModel interface {
		Insert(ctx context.Context, data *Executions) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *Executions) (*Executions, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*Executions) ([]*Executions, error)
		FindOne(ctx context.Context, id int64) (*Executions, error)
		Update(ctx context.Context, data *Executions) error
		Delete(ctx context.Context, id int64) error
	}

	defaultExecutionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Executions struct {
		Id        int64     `db:"id"`         // 流水 ID
		OrderId   int64     `db:"order_id"`   // 关联的本地 Orders ID
		ClientOid string    `db:"client_oid"` // 关联的本地 ClientOid
		ExecId    string    `db:"exec_id"`    // 交易所成交 ID (Trade ID)
		Symbol    string    `db:"symbol"`     // 交易对
		Side      string    `db:"side"`       // 成交方向 [ENUM: BUY, SELL]
		Price     float64   `db:"price"`      // 成交价格
		Quantity  float64   `db:"quantity"`   // 成交数量
		QuoteQty  float64   `db:"quote_qty"`  // 成交金额 (Quote Asset)
		Fee       float64   `db:"fee"`        // 手续费数值
		FeeAsset  string    `db:"fee_asset"`  // 手续费计价币种
		TradedAt  time.Time `db:"traded_at"`  // 交易所成交撮合时间
		CreatedAt time.Time `db:"created_at"` // 记录存库时间
	}
)

func newExecutionsModel(conn sqlx.SqlConn) *defaultExecutionsModel {
	return &defaultExecutionsModel{
		conn:  conn,
		table: "\"public\".\"executions\"",
	}
}

func (m *defaultExecutionsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultExecutionsModel) FindOne(ctx context.Context, id int64) (*Executions, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", executionsRows, m.table)
	var resp Executions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultExecutionsModel) Insert(ctx context.Context, data *Executions) (sql.Result, error) {
	builder := m.insertBuilder().Columns(executionsRowsExpectAutoSet).Values(data.OrderId, data.ClientOid, data.ExecId, data.Symbol, data.Side, data.Price, data.Quantity, data.QuoteQty, data.Fee, data.FeeAsset, data.TradedAt, data.CreatedAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultExecutionsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*Executions) ([]*Executions, error) {
	builder := m.insertBuilder().Columns(executionsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.OrderId, data.ClientOid, data.ExecId, data.Symbol, data.Side, data.Price, data.Quantity, data.QuoteQty, data.Fee, data.FeeAsset, data.TradedAt, data.CreatedAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultExecutionsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *Executions) (*Executions, error) {
	builder := m.insertBuilder().Columns(executionsRowsExpectAutoSet).Values(data.OrderId, data.ClientOid, data.ExecId, data.Symbol, data.Side, data.Price, data.Quantity, data.QuoteQty, data.Fee, data.FeeAsset, data.TradedAt, data.CreatedAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultExecutionsModel) Update(ctx context.Context, newData *Executions) error {
	builder := m.updateBuilder()
	builder = builder.Set("order_id", newData.OrderId)
	builder = builder.Set("client_oid", newData.ClientOid)
	builder = builder.Set("exec_id", newData.ExecId)
	builder = builder.Set("symbol", newData.Symbol)
	builder = builder.Set("side", newData.Side)
	builder = builder.Set("price", newData.Price)
	builder = builder.Set("quantity", newData.Quantity)
	builder = builder.Set("quote_qty", newData.QuoteQty)
	builder = builder.Set("fee", newData.Fee)
	builder = builder.Set("fee_asset", newData.FeeAsset)
	builder = builder.Set("traded_at", newData.TradedAt)
	builder = builder.Set("created_at", newData.CreatedAt)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultExecutionsModel) tableName() string {
	return m.table
}

func (m *defaultExecutionsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultExecutionsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExecutionsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExecutionsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExecutionsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultExecutionsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultExecutionsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*Executions, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Executions
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultExecutionsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*Executions, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp Executions
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultExecutionsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultExecutionsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*Executions, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Executions
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultExecutionsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultExecutionsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultExecutionsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(executionsFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultExecutionsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultExecutionsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*Executions, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Executions
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultExecutionsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*Executions, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Executions
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
