// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:07Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	riskRecordsFieldNames        = builder.RawFieldNames(&RiskRecords{}, true)
	riskRecordsRows              = strings.Join(riskRecordsFieldNames, ",")
	riskRecordsRowsExpectAutoSet = strings.Join(stringx.Remove(riskRecordsFieldNames, "id"), ",")
)

type (
	riskRecordsModel interface {
		Insert(ctx context.Context, data *RiskRecords) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *RiskRecords) (*RiskRecords, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*RiskRecords) ([]*RiskRecords, error)
		FindOne(ctx context.Context, id int64) (*RiskRecords, error)
		Update(ctx context.Context, data *RiskRecords) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRiskRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RiskRecords struct {
		Id          int64     `db:"id"`           // 流水 ID
		EventType   string    `db:"event_type"`   // 事件类型 [ENUM: POS_LIMIT, LOSS_CIRCUIT, SLIPPAGE, PRICE_PROTECT]
		Level       string    `db:"level"`        // 风险级别 [ENUM: INFO, WARNING, BLOCK, CRITICAL]
		Symbol      string    `db:"symbol"`       // 涉及标的
		StrategyId  string    `db:"strategy_id"`  // 涉及策略
		Details     string    `db:"details"`      // 触发时的上下文快照 [JSON]
		TriggeredAt time.Time `db:"triggered_at"` // 触发时间
	}
)

func newRiskRecordsModel(conn sqlx.SqlConn) *defaultRiskRecordsModel {
	return &defaultRiskRecordsModel{
		conn:  conn,
		table: "\"public\".\"risk_records\"",
	}
}

func (m *defaultRiskRecordsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRiskRecordsModel) FindOne(ctx context.Context, id int64) (*RiskRecords, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", riskRecordsRows, m.table)
	var resp RiskRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultRiskRecordsModel) Insert(ctx context.Context, data *RiskRecords) (sql.Result, error) {
	builder := m.insertBuilder().Columns(riskRecordsRowsExpectAutoSet).Values(data.EventType, data.Level, data.Symbol, data.StrategyId, data.Details, data.TriggeredAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultRiskRecordsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*RiskRecords) ([]*RiskRecords, error) {
	builder := m.insertBuilder().Columns(riskRecordsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.EventType, data.Level, data.Symbol, data.StrategyId, data.Details, data.TriggeredAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultRiskRecordsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *RiskRecords) (*RiskRecords, error) {
	builder := m.insertBuilder().Columns(riskRecordsRowsExpectAutoSet).Values(data.EventType, data.Level, data.Symbol, data.StrategyId, data.Details, data.TriggeredAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultRiskRecordsModel) Update(ctx context.Context, newData *RiskRecords) error {
	builder := m.updateBuilder()
	builder = builder.Set("event_type", newData.EventType)
	builder = builder.Set("level", newData.Level)
	builder = builder.Set("symbol", newData.Symbol)
	builder = builder.Set("strategy_id", newData.StrategyId)
	builder = builder.Set("details", newData.Details)
	builder = builder.Set("triggered_at", newData.TriggeredAt)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultRiskRecordsModel) tableName() string {
	return m.table
}

func (m *defaultRiskRecordsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultRiskRecordsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultRiskRecordsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultRiskRecordsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultRiskRecordsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultRiskRecordsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultRiskRecordsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*RiskRecords, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*RiskRecords
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultRiskRecordsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*RiskRecords, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp RiskRecords
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultRiskRecordsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultRiskRecordsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*RiskRecords, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*RiskRecords
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultRiskRecordsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultRiskRecordsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultRiskRecordsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(riskRecordsFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultRiskRecordsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultRiskRecordsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*RiskRecords, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*RiskRecords
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultRiskRecordsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*RiskRecords, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*RiskRecords
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
