// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:07Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	settlementsFieldNames        = builder.RawFieldNames(&Settlements{}, true)
	settlementsRows              = strings.Join(settlementsFieldNames, ",")
	settlementsRowsExpectAutoSet = strings.Join(stringx.Remove(settlementsFieldNames, "id"), ",")
)

type (
	settlementsModel interface {
		Insert(ctx context.Context, data *Settlements) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *Settlements) (*Settlements, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*Settlements) ([]*Settlements, error)
		FindOne(ctx context.Context, id int64) (*Settlements, error)
		Update(ctx context.Context, data *Settlements) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSettlementsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Settlements struct {
		Id              int64     `db:"id"`               // 结算单 ID
		TradeId         string    `db:"trade_id"`         // 逻辑交易 ID (跨订单关联标识)
		Symbol          string    `db:"symbol"`           // 交易对
		MarketType      string    `db:"market_type"`      // 市场类型 [ENUM: SPOT, SWAP, FUTURE]
		Side            string    `db:"side"`             // 盈亏方向 [ENUM: LONG, SHORT]
		RealizedPnl     float64   `db:"realized_pnl"`     // 已实现净盈亏 (扣费后)
		Commission      float64   `db:"commission"`       // 累计手续费支出
		FundingFee      float64   `db:"funding_fee"`      // 累计资金费支出 (仅限合约)
		EntryPrice      float64   `db:"entry_price"`      // 平均开仓价
		ExitPrice       float64   `db:"exit_price"`       // 平均平仓价
		Quantity        float64   `db:"quantity"`         // 结算头寸数量
		Roi             float64   `db:"roi"`              // 收益率百分比
		OpenedAt        time.Time `db:"opened_at"`        // 逻辑开仓时间
		ClosedAt        time.Time `db:"closed_at"`        // 逻辑平仓时间
		DurationSeconds int64     `db:"duration_seconds"` // 持仓总时长 (秒)
		Metadata        string    `db:"metadata"`         // 扩展元数据 [JSON: leverage, liq_price]
		CreatedAt       time.Time `db:"created_at"`       // 记录生成时间
	}
)

func newSettlementsModel(conn sqlx.SqlConn) *defaultSettlementsModel {
	return &defaultSettlementsModel{
		conn:  conn,
		table: "\"public\".\"settlements\"",
	}
}

func (m *defaultSettlementsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSettlementsModel) FindOne(ctx context.Context, id int64) (*Settlements, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", settlementsRows, m.table)
	var resp Settlements
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultSettlementsModel) Insert(ctx context.Context, data *Settlements) (sql.Result, error) {
	builder := m.insertBuilder().Columns(settlementsRowsExpectAutoSet).Values(data.TradeId, data.Symbol, data.MarketType, data.Side, data.RealizedPnl, data.Commission, data.FundingFee, data.EntryPrice, data.ExitPrice, data.Quantity, data.Roi, data.OpenedAt, data.ClosedAt, data.DurationSeconds, data.Metadata, data.CreatedAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultSettlementsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*Settlements) ([]*Settlements, error) {
	builder := m.insertBuilder().Columns(settlementsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.TradeId, data.Symbol, data.MarketType, data.Side, data.RealizedPnl, data.Commission, data.FundingFee, data.EntryPrice, data.ExitPrice, data.Quantity, data.Roi, data.OpenedAt, data.ClosedAt, data.DurationSeconds, data.Metadata, data.CreatedAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultSettlementsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *Settlements) (*Settlements, error) {
	builder := m.insertBuilder().Columns(settlementsRowsExpectAutoSet).Values(data.TradeId, data.Symbol, data.MarketType, data.Side, data.RealizedPnl, data.Commission, data.FundingFee, data.EntryPrice, data.ExitPrice, data.Quantity, data.Roi, data.OpenedAt, data.ClosedAt, data.DurationSeconds, data.Metadata, data.CreatedAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultSettlementsModel) Update(ctx context.Context, newData *Settlements) error {
	builder := m.updateBuilder()
	builder = builder.Set("trade_id", newData.TradeId)
	builder = builder.Set("symbol", newData.Symbol)
	builder = builder.Set("market_type", newData.MarketType)
	builder = builder.Set("side", newData.Side)
	builder = builder.Set("realized_pnl", newData.RealizedPnl)
	builder = builder.Set("commission", newData.Commission)
	builder = builder.Set("funding_fee", newData.FundingFee)
	builder = builder.Set("entry_price", newData.EntryPrice)
	builder = builder.Set("exit_price", newData.ExitPrice)
	builder = builder.Set("quantity", newData.Quantity)
	builder = builder.Set("roi", newData.Roi)
	builder = builder.Set("opened_at", newData.OpenedAt)
	builder = builder.Set("closed_at", newData.ClosedAt)
	builder = builder.Set("duration_seconds", newData.DurationSeconds)
	builder = builder.Set("metadata", newData.Metadata)
	builder = builder.Set("created_at", newData.CreatedAt)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultSettlementsModel) tableName() string {
	return m.table
}

func (m *defaultSettlementsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultSettlementsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultSettlementsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultSettlementsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultSettlementsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultSettlementsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultSettlementsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*Settlements, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Settlements
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultSettlementsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*Settlements, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp Settlements
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultSettlementsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultSettlementsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*Settlements, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Settlements
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultSettlementsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultSettlementsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultSettlementsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(settlementsFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultSettlementsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultSettlementsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*Settlements, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Settlements
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultSettlementsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*Settlements, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Settlements
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
