// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:07Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	strategyConfigsFieldNames        = builder.RawFieldNames(&StrategyConfigs{}, true)
	strategyConfigsRows              = strings.Join(strategyConfigsFieldNames, ",")
	strategyConfigsRowsExpectAutoSet = strings.Join(stringx.Remove(strategyConfigsFieldNames), ",")
)

type (
	strategyConfigsModel interface {
		Insert(ctx context.Context, data *StrategyConfigs) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *StrategyConfigs) (*StrategyConfigs, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*StrategyConfigs) ([]*StrategyConfigs, error)
		FindOne(ctx context.Context, keyName string) (*StrategyConfigs, error)
		Update(ctx context.Context, data *StrategyConfigs) error
		Delete(ctx context.Context, keyName string) error
	}

	defaultStrategyConfigsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	StrategyConfigs struct {
		KeyName     string    `db:"key_name"`    // 配置键名 (e.g., risk.max_pos_ratio)
		ValueStr    string    `db:"value_str"`   // 字符串类型值
		ValueNum    float64   `db:"value_num"`   // 数值类型值
		Description string    `db:"description"` // 配置项含义描述
		UpdatedAt   time.Time `db:"updated_at"`  // 最后修改时间
	}
)

func newStrategyConfigsModel(conn sqlx.SqlConn) *defaultStrategyConfigsModel {
	return &defaultStrategyConfigsModel{
		conn:  conn,
		table: "\"public\".\"strategy_configs\"",
	}
}

func (m *defaultStrategyConfigsModel) Delete(ctx context.Context, keyName string) error {
	query := fmt.Sprintf("delete from %s where key_name = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, keyName)
	return err
}

func (m *defaultStrategyConfigsModel) FindOne(ctx context.Context, keyName string) (*StrategyConfigs, error) {
	query := fmt.Sprintf("select %s from %s where key_name = $1 limit 1", strategyConfigsRows, m.table)
	var resp StrategyConfigs
	err := m.conn.QueryRowCtx(ctx, &resp, query, keyName)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultStrategyConfigsModel) Insert(ctx context.Context, data *StrategyConfigs) (sql.Result, error) {
	builder := m.insertBuilder().Columns(strategyConfigsRowsExpectAutoSet).Values(data.KeyName, data.ValueStr, data.ValueNum, data.Description, data.UpdatedAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultStrategyConfigsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*StrategyConfigs) ([]*StrategyConfigs, error) {
	builder := m.insertBuilder().Columns(strategyConfigsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.KeyName, data.ValueStr, data.ValueNum, data.Description, data.UpdatedAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultStrategyConfigsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *StrategyConfigs) (*StrategyConfigs, error) {
	builder := m.insertBuilder().Columns(strategyConfigsRowsExpectAutoSet).Values(data.KeyName, data.ValueStr, data.ValueNum, data.Description, data.UpdatedAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultStrategyConfigsModel) Update(ctx context.Context, newData *StrategyConfigs) error {
	builder := m.updateBuilder()
	builder = builder.Set("value_str", newData.ValueStr)
	builder = builder.Set("value_num", newData.ValueNum)
	builder = builder.Set("description", newData.Description)
	builder = builder.Set("updated_at", newData.UpdatedAt)
	builder = builder.Where(squirrel.Eq{
		"key_name": newData.KeyName,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultStrategyConfigsModel) tableName() string {
	return m.table
}

func (m *defaultStrategyConfigsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultStrategyConfigsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultStrategyConfigsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultStrategyConfigsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultStrategyConfigsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultStrategyConfigsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultStrategyConfigsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*StrategyConfigs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*StrategyConfigs
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultStrategyConfigsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*StrategyConfigs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp StrategyConfigs
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultStrategyConfigsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".key_name)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultStrategyConfigsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*StrategyConfigs, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*StrategyConfigs
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultStrategyConfigsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultStrategyConfigsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultStrategyConfigsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(strategyConfigsFieldNames, orderBy) {
		orderBy = "key_name"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultStrategyConfigsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultStrategyConfigsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*StrategyConfigs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*StrategyConfigs
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultStrategyConfigsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*StrategyConfigs, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*StrategyConfigs
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
