// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:06Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames        = builder.RawFieldNames(&Users{}, true)
	usersRows              = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet = strings.Join(stringx.Remove(usersFieldNames, "id"), ",")
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *Users) (*Users, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*Users) ([]*Users, error)
		FindOne(ctx context.Context, id int64) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		Id                int64          `db:"id"`                  // 内部自增主键
		Uuid              string         `db:"uuid"`                // WebAuthn User Handle (UUID)
		Username          string         `db:"username"`            // 登录用户名
		DisplayName       string         `db:"display_name"`        // 用户显示名称
		Avatar            string         `db:"avatar"`              // 用户头像 URL
		PasswordHash      string         `db:"password_hash"`       // 静态密码哈希：仅用于 Break-Glass 紧急恢复 (Argon2id)
		PasswordUpdatedAt time.Time      `db:"password_updated_at"` // 密码最后修改时间，用于强制过期校验
		IsActive          bool           `db:"is_active"`           // 账号激活状态
		RevokedAt         time.Time      `db:"revoked_at"`          // 令牌撤销基准时间
		GithubId          sql.NullString `db:"github_id"`           // GitHub 唯一标识
		GoogleId          sql.NullString `db:"google_id"`           // Google 唯一标识
		CreatedAt         time.Time      `db:"created_at"`          // 账号创建时间
		UpdatedAt         time.Time      `db:"updated_at"`          // 最后更新时间
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: "\"public\".\"users\"",
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, id int64) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	builder := m.insertBuilder().Columns(usersRowsExpectAutoSet).Values(data.Uuid, data.Username, data.DisplayName, data.Avatar, data.PasswordHash, data.PasswordUpdatedAt, data.IsActive, data.RevokedAt, data.GithubId, data.GoogleId, data.CreatedAt, data.UpdatedAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultUsersModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*Users) ([]*Users, error) {
	builder := m.insertBuilder().Columns(usersRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.Uuid, data.Username, data.DisplayName, data.Avatar, data.PasswordHash, data.PasswordUpdatedAt, data.IsActive, data.RevokedAt, data.GithubId, data.GoogleId, data.CreatedAt, data.UpdatedAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultUsersModel) InsertReturn(ctx context.Context, session sqlx.Session, data *Users) (*Users, error) {
	builder := m.insertBuilder().Columns(usersRowsExpectAutoSet).Values(data.Uuid, data.Username, data.DisplayName, data.Avatar, data.PasswordHash, data.PasswordUpdatedAt, data.IsActive, data.RevokedAt, data.GithubId, data.GoogleId, data.CreatedAt, data.UpdatedAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	builder := m.updateBuilder()
	builder = builder.Set("uuid", newData.Uuid)
	builder = builder.Set("username", newData.Username)
	builder = builder.Set("display_name", newData.DisplayName)
	builder = builder.Set("avatar", newData.Avatar)
	builder = builder.Set("password_hash", newData.PasswordHash)
	builder = builder.Set("is_active", newData.IsActive)
	builder = builder.Set("revoked_at", newData.RevokedAt)
	builder = builder.Set("github_id", newData.GithubId)
	builder = builder.Set("google_id", newData.GoogleId)
	builder = builder.Set("created_at", newData.CreatedAt)
	builder = builder.Set("updated_at", newData.UpdatedAt)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}

func (m *defaultUsersModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultUsersModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultUsersModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultUsersModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultUsersModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultUsersModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultUsersModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*Users, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Users
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultUsersModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*Users, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp Users
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultUsersModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultUsersModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*Users, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Users
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultUsersModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultUsersModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultUsersModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(usersFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultUsersModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultUsersModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*Users, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Users
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultUsersModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*Users, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*Users
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
