// Code generated by pgmodelgen. DO NOT EDIT.
// generated_at_utc: 2026-01-01T07:04:06Z
// version: 0.1.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"strings"
	"time"
)

var (
	webauthnCredentialsFieldNames        = builder.RawFieldNames(&WebauthnCredentials{}, true)
	webauthnCredentialsRows              = strings.Join(webauthnCredentialsFieldNames, ",")
	webauthnCredentialsRowsExpectAutoSet = strings.Join(stringx.Remove(webauthnCredentialsFieldNames, "id"), ",")
)

type (
	webauthnCredentialsModel interface {
		Insert(ctx context.Context, data *WebauthnCredentials) (sql.Result, error)
		InsertReturn(ctx context.Context, session sqlx.Session, data *WebauthnCredentials) (*WebauthnCredentials, error)
		BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*WebauthnCredentials) ([]*WebauthnCredentials, error)
		FindOne(ctx context.Context, id int64) (*WebauthnCredentials, error)
		Update(ctx context.Context, data *WebauthnCredentials) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWebauthnCredentialsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WebauthnCredentials struct {
		Id              int64     `db:"id"`               // 凭证自增 ID
		UserId          int64     `db:"user_id"`          // 关联的用户 ID
		WebauthnId      string    `db:"webauthn_id"`      // 浏览器返回的唯一凭证 ID
		PublicKey       string    `db:"public_key"`       // COSE 编码的认证公钥
		AttestationType string    `db:"attestation_type"` // 认证器声明类型
		Transport       string    `db:"transport"`        // 支持的传输协议 [ENUM: usb, nfc, ble, internal, hybrid]
		Aaguid          string    `db:"aaguid"`           // 验证器型号唯一标识
		SignCount       int64     `db:"sign_count"`       // 签名计数器：用于检测凭证克隆风险
		CloneWarning    bool      `db:"clone_warning"`    // 凭证是否存在克隆嫌疑标记
		DeviceName      string    `db:"device_name"`      // 用户定义的硬件设备名称
		CreatedAt       time.Time `db:"created_at"`       // 凭证注册时间
		LastUsedAt      time.Time `db:"last_used_at"`     // 最后一次认证时间
	}
)

func newWebauthnCredentialsModel(conn sqlx.SqlConn) *defaultWebauthnCredentialsModel {
	return &defaultWebauthnCredentialsModel{
		conn:  conn,
		table: "\"public\".\"webauthn_credentials\"",
	}
}

func (m *defaultWebauthnCredentialsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWebauthnCredentialsModel) FindOne(ctx context.Context, id int64) (*WebauthnCredentials, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", webauthnCredentialsRows, m.table)
	var resp WebauthnCredentials
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *defaultWebauthnCredentialsModel) Insert(ctx context.Context, data *WebauthnCredentials) (sql.Result, error) {
	builder := m.insertBuilder().Columns(webauthnCredentialsRowsExpectAutoSet).Values(data.UserId, data.WebauthnId, data.PublicKey, data.AttestationType, data.Transport, data.Aaguid, data.SignCount, data.CloneWarning, data.DeviceName, data.CreatedAt, data.LastUsedAt)
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	return m.conn.ExecCtx(ctx, querySql, values...)
}

func (m *defaultWebauthnCredentialsModel) BatchInsertReturn(ctx context.Context, session sqlx.Session, dataList []*WebauthnCredentials) ([]*WebauthnCredentials, error) {
	builder := m.insertBuilder().Columns(webauthnCredentialsRowsExpectAutoSet)
	for _, data := range dataList {
		builder = builder.Values(data.UserId, data.WebauthnId, data.PublicKey, data.AttestationType, data.Transport, data.Aaguid, data.SignCount, data.CloneWarning, data.DeviceName, data.CreatedAt, data.LastUsedAt)
	}
	return m.insertListWithReturn(ctx, session, builder)
}

func (m *defaultWebauthnCredentialsModel) InsertReturn(ctx context.Context, session sqlx.Session, data *WebauthnCredentials) (*WebauthnCredentials, error) {
	builder := m.insertBuilder().Columns(webauthnCredentialsRowsExpectAutoSet).Values(data.UserId, data.WebauthnId, data.PublicKey, data.AttestationType, data.Transport, data.Aaguid, data.SignCount, data.CloneWarning, data.DeviceName, data.CreatedAt, data.LastUsedAt)
	return m.insertWithReturn(ctx, session, builder)
}

func (m *defaultWebauthnCredentialsModel) Update(ctx context.Context, newData *WebauthnCredentials) error {
	builder := m.updateBuilder()
	builder = builder.Set("user_id", newData.UserId)
	builder = builder.Set("webauthn_id", newData.WebauthnId)
	builder = builder.Set("public_key", newData.PublicKey)
	builder = builder.Set("attestation_type", newData.AttestationType)
	builder = builder.Set("transport", newData.Transport)
	builder = builder.Set("aaguid", newData.Aaguid)
	builder = builder.Set("sign_count", newData.SignCount)
	builder = builder.Set("clone_warning", newData.CloneWarning)
	builder = builder.Set("device_name", newData.DeviceName)
	builder = builder.Set("created_at", newData.CreatedAt)
	builder = builder.Set("last_used_at", newData.LastUsedAt)
	builder = builder.Where(squirrel.Eq{
		"id": newData.Id,
	})
	return m.execCtxWithSession(ctx, nil, builder)
}

func (m *defaultWebauthnCredentialsModel) tableName() string {
	return m.table
}

func (m *defaultWebauthnCredentialsModel) selectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().PlaceholderFormat(squirrel.Dollar).From(m.table)
}

func (m *defaultWebauthnCredentialsModel) insertBuilder() squirrel.InsertBuilder {
	return squirrel.Insert(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultWebauthnCredentialsModel) replaceBuilder() squirrel.InsertBuilder {
	return squirrel.Replace(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultWebauthnCredentialsModel) updateBuilder() squirrel.UpdateBuilder {
	return squirrel.Update(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultWebauthnCredentialsModel) deleteBuilder() squirrel.DeleteBuilder {
	return squirrel.Delete(m.table).PlaceholderFormat(squirrel.Dollar)
}

func (m *defaultWebauthnCredentialsModel) execCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) error {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	if session != nil {
		_, err = session.Exec(sqlStr, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, sqlStr, args...)
	}
	return err
}

func (m *defaultWebauthnCredentialsModel) insertListWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) ([]*WebauthnCredentials, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*WebauthnCredentials
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

func (m *defaultWebauthnCredentialsModel) insertWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.InsertBuilder) (*WebauthnCredentials, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp WebauthnCredentials
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, querySql, values...)
	}
	return &resp, err
}

// findCount 根据squirrel.SelectBuilder生成的sql查询当前表条数
func (m *defaultWebauthnCredentialsModel) findCount(ctx context.Context, builder squirrel.SelectBuilder) (int64, error) {
	builder = builder.Columns("COUNT(" + m.tableName() + ".id)")
	query, values, err := builder.ToSql()
	if err != nil {
		return 0, err
	}
	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	if err != nil {
		return 0, err
	}
	return resp, nil
}

// findList 根据squirrel.SelectBuilder生成的sql查询当前表所有字段返回对象
func (m *defaultWebauthnCredentialsModel) findList(ctx context.Context, builder squirrel.SelectBuilder) ([]*WebauthnCredentials, error) {
	builder = builder.Columns(m.tableName() + ".*")
	querySql, values, err := builder.ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*WebauthnCredentials
	err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	return resp, err
}

// findListWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultWebauthnCredentialsModel) findListWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowsCtx(ctx, v, querySql, values...)
}

// findWithAny 根据squirrel.SelectBuilder生成的sql查询指定的
func (m *defaultWebauthnCredentialsModel) findWithAny(ctx context.Context, sqlizer squirrel.Sqlizer, v any) error {
	querySql, values, err := sqlizer.ToSql()
	if err != nil {
		return err
	}
	return m.conn.QueryRowCtx(ctx, v, querySql, values...)
}

// buildPageQuery 构建分页条件
func (m *defaultWebauthnCredentialsModel) buildPageQuery(builder squirrel.SelectBuilder, offset int64, limit int64, orderBy string, isAsc bool) squirrel.SelectBuilder {
	builder = builder.Offset(uint64(offset))
	if limit > 0 {
		builder = builder.Limit(uint64(limit))
	}
	orderType := "DESC"
	if isAsc {
		orderType = "ASC"
	}
	if !stringx.Contains(webauthnCredentialsFieldNames, orderBy) {
		orderBy = "id"
	}
	return builder.OrderBy(fmt.Sprintf("%s %s", orderBy, orderType))
}

// execResultCtxWithSession 根据sqlizer生产sql执行并返回结果
func (m *defaultWebauthnCredentialsModel) execResultCtxWithSession(ctx context.Context, session sqlx.Session, sqlizer squirrel.Sqlizer) (sql.Result, error) {
	sqlStr, args, err := sqlizer.ToSql()
	if err != nil {
		return nil, err
	}
	if session != nil {
		return session.Exec(sqlStr, args...)
	}
	return m.conn.ExecCtx(ctx, sqlStr, args...)
}

// updateWithReturn 根据squirrel.UpdateBuilder条件构建更新语句并返回更新后的对象
func (m *defaultWebauthnCredentialsModel) updateWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.UpdateBuilder) ([]*WebauthnCredentials, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*WebauthnCredentials
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}

// deleteWithReturn 根据squirrel.DeleteBuilder条件构建删除语句并返回被删除的对象
func (m *defaultWebauthnCredentialsModel) deleteWithReturn(ctx context.Context, session sqlx.Session, sqlizer squirrel.DeleteBuilder) ([]*WebauthnCredentials, error) {
	querySql, values, err := sqlizer.Suffix("RETURNING *").ToSql()
	if err != nil {
		return nil, err
	}
	var resp []*WebauthnCredentials
	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, querySql, values...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, querySql, values...)
	}
	return resp, err
}
