// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/Masterminds/squirrel"
)

// assetSnapshots is the query entry point for AssetSnapshots
var assetSnapshots = newAssetSnapshotsQuery()

// newAssetSnapshotsQuery creates a new query builder for AssetSnapshots
func newAssetSnapshotsQuery() *assetSnapshotsQuery {
	return &assetSnapshotsQuery{
		fieldMap: map[string]Field{
			"id":                assetSnapshotsField.ID,
			"exchange":          assetSnapshotsField.Exchange,
			"total_balance":     assetSnapshotsField.TotalBalance,
			"available_balance": assetSnapshotsField.AvailableBalance,
			"frozen_balance":    assetSnapshotsField.FrozenBalance,
			"snapshot_time":     assetSnapshotsField.SnapshotTime,
		},
	}
}

// assetSnapshotsQuery is the query builder for AssetSnapshots
type assetSnapshotsQuery struct {
	db       Executor
	fieldMap map[string]Field
}

// assetSnapshotsField provides type-safe field access for AssetSnapshots
var assetSnapshotsField = struct {
	ID               Int64Field
	Exchange         StringField
	TotalBalance     DecimalField
	AvailableBalance DecimalField
	FrozenBalance    DecimalField
	SnapshotTime     TimeField
}{
	ID:               Int64Field("id"),
	Exchange:         StringField("exchange"),
	TotalBalance:     DecimalField("total_balance"),
	AvailableBalance: DecimalField("available_balance"),
	FrozenBalance:    DecimalField("frozen_balance"),
	SnapshotTime:     TimeField("snapshot_time"),
}

// WithDB returns a new query instance with the given database executor
func (q *assetSnapshotsQuery) WithDB(db Executor) IAssetSnapshotsDo {
	return &assetSnapshotsDo{
		db:    db,
		table: "\"public\".\"asset_snapshots\"",
		columns: []string{
			"id",
			"exchange",
			"total_balance",
			"available_balance",
			"frozen_balance",
			"snapshot_time",
		},
	}
}

// As creates a table alias for the query
func (q *assetSnapshotsQuery) As(alias string) *assetSnapshotsQuery {
	return q
}

// IAssetSnapshotsDo defines the interface for AssetSnapshots data operations
type IAssetSnapshotsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *AssetSnapshots) (*AssetSnapshots, error)
	BatchCreate(ctx context.Context, models []*AssetSnapshots) ([]*AssetSnapshots, error)
	FindByPK(ctx context.Context, iD int64) (*AssetSnapshots, error)
	FindByIndex(ctx context.Context, req *AssetSnapshotsIndex) ([]*AssetSnapshotsIndex, error)
	UpdateByPK(ctx context.Context, model *AssetSnapshots) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *AssetSnapshots) (*AssetSnapshots, error)
	UpsertAll(ctx context.Context, model *AssetSnapshots) (*AssetSnapshots, error)

	// Query builder (type-safe, only accepts fields from this table)
	Where(conds ...WhereCondition) IAssetSnapshotsDo
	Select(fields ...Field) IAssetSnapshotsDo
	Order(orderBys ...OrderByClause) IAssetSnapshotsDo
	Limit(limit int) IAssetSnapshotsDo
	Offset(offset int) IAssetSnapshotsDo

	// Execution methods
	Find(ctx context.Context) ([]*AssetSnapshots, error)
	First(ctx context.Context) (*AssetSnapshots, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IAssetSnapshotsDo
}

// Ensure assetSnapshotsDo implements IAssetSnapshotsDo
var _ IAssetSnapshotsDo = (*assetSnapshotsDo)(nil)

// assetSnapshotsDo wraps the query builder with chainable methods
type assetSnapshotsDo struct {
	db      Executor
	table   string
	columns []string
	builder squirrel.SelectBuilder

	// Query state
	whereSet  bool
	selectSet bool
	orderSet  bool
	limitSet  bool
	offsetSet bool
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *assetSnapshotsDo) WithDB(db Executor) IAssetSnapshotsDo {
	return &assetSnapshotsDo{
		db:      db,
		table:   d.table,
		columns: d.columns,
	}
}

// Where adds WHERE conditions (chainable)
func (d *assetSnapshotsDo) Where(conds ...WhereCondition) IAssetSnapshotsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		d.builder = d.builder.Where(cond.ToSqlizer())
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *assetSnapshotsDo) Select(fields ...Field) IAssetSnapshotsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., assetSnapshotsField.Age.Desc())
func (d *assetSnapshotsDo) Order(orderBys ...OrderByClause) IAssetSnapshotsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *assetSnapshotsDo) Limit(limit int) IAssetSnapshotsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *assetSnapshotsDo) Offset(offset int) IAssetSnapshotsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *assetSnapshotsDo) Find(ctx context.Context) ([]*AssetSnapshots, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	defer rows.Close()

	var results []*AssetSnapshots
	for rows.Next() {
		var result AssetSnapshots
		err := rows.Scan(
			&result.ID,
			&result.Exchange,
			&result.TotalBalance,
			&result.AvailableBalance,
			&result.FrozenBalance,
			&result.SnapshotTime,
		)
		if err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// First executes the query and returns the first matching record
func (d *assetSnapshotsDo) First(ctx context.Context) (*AssetSnapshots, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result AssetSnapshots
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.Exchange,
		&result.TotalBalance,
		&result.AvailableBalance,
		&result.FrozenBalance,
		&result.SnapshotTime,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *assetSnapshotsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.table).PlaceholderFormat(squirrel.Dollar)

	if d.whereSet {
		// Extract WHERE clauses from existing builder if any
		query, args, err := d.builder.ToSql()
		if err != nil {
			return 0, fmt.Errorf("build count query: %w", err)
		}
		// Parse WHERE clause from the query
		_ = query // TODO: extract WHERE clause properly
		_ = args
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowContext(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *assetSnapshotsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *assetSnapshotsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
