// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/Masterminds/squirrel"
	"github.com/shopspring/decimal"
	"strings"
	"time"
)

// AssetSnapshots represents a row in table "public"."asset_snapshots".
//
// Indexes:
//   - asset_snapshots_pkey (PRIMARY KEY) (btree): id
type AssetSnapshots struct {
	ID               int64           `db:"id" json:"id"`                               // 流水 ID
	Exchange         string          `db:"exchange" json:"exchange"`                   // 交易所类型
	TotalBalance     decimal.Decimal `db:"total_balance" json:"total_balance"`         // 总权益估值 (USDT)
	AvailableBalance decimal.Decimal `db:"available_balance" json:"available_balance"` // 可用余额 (USDT)
	FrozenBalance    decimal.Decimal `db:"frozen_balance" json:"frozen_balance"`       // 冻结金额 (USDT)
	SnapshotTime     time.Time       `db:"snapshot_time" json:"snapshot_time"`         // 快照生成时间
}

// TableName returns the table name for AssetSnapshots
func (m *AssetSnapshots) TableName() string {
	return "public.asset_snapshots"
}

// AssetSnapshotsIndex represents indexed columns for covering index queries.
// Only includes columns that appear in at least one index, enabling index-only scans.
type AssetSnapshotsIndex struct {
	ID int64 `db:"id" json:"id"` // 流水 ID
}

// Create inserts a new record and returns the inserted record with auto-generated fields
func (d *assetSnapshotsDo) Create(ctx context.Context, model *AssetSnapshots) (*AssetSnapshots, error) {
	builder := squirrel.Insert(d.table).
		PlaceholderFormat(squirrel.Dollar).
		Columns("exchange", "total_balance", "available_balance", "frozen_balance", "snapshot_time").
		Values(model.Exchange, model.TotalBalance, model.AvailableBalance, model.FrozenBalance, model.SnapshotTime).
		Suffix("RETURNING " + strings.Join(d.columns, ", "))

	query, args, err := builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build insert query: %w", err)
	}

	var result AssetSnapshots
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.Exchange,
		&result.TotalBalance,
		&result.AvailableBalance,
		&result.FrozenBalance,
		&result.SnapshotTime,
	)
	if err != nil {
		return nil, fmt.Errorf("insert: %w", err)
	}
	return &result, nil
}

// BatchCreate inserts multiple records and returns all inserted records
func (d *assetSnapshotsDo) BatchCreate(ctx context.Context, models []*AssetSnapshots) ([]*AssetSnapshots, error) {
	if len(models) == 0 {
		return nil, nil
	}

	builder := squirrel.Insert(d.table).
		PlaceholderFormat(squirrel.Dollar).
		Columns("exchange", "total_balance", "available_balance", "frozen_balance", "snapshot_time")

	for _, model := range models {
		builder = builder.Values(model.Exchange, model.TotalBalance, model.AvailableBalance, model.FrozenBalance, model.SnapshotTime)
	}

	builder = builder.Suffix("RETURNING " + strings.Join(d.columns, ", "))
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build batch insert query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("batch insert: %w", err)
	}
	defer rows.Close()

	var results []*AssetSnapshots
	for rows.Next() {
		var result AssetSnapshots
		err := rows.Scan(
			&result.ID,
			&result.Exchange,
			&result.TotalBalance,
			&result.AvailableBalance,
			&result.FrozenBalance,
			&result.SnapshotTime,
		)
		if err != nil {
			return nil, fmt.Errorf("scan batch insert result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// FindByPK finds a record by primary key
func (d *assetSnapshotsDo) FindByPK(ctx context.Context, iD int64) (*AssetSnapshots, error) {
	builder := squirrel.Select(d.columns...).
		From(d.table).
		PlaceholderFormat(squirrel.Dollar).
		Where(squirrel.Eq{
			"id": iD,
		}).
		Limit(1)

	query, args, err := builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build select query: %w", err)
	}

	var result AssetSnapshots
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.Exchange,
		&result.TotalBalance,
		&result.AvailableBalance,
		&result.FrozenBalance,
		&result.SnapshotTime,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("find by pk: %w", err)
	}
	return &result, nil
}

// UpdateByPK updates a record by primary key
func (d *assetSnapshotsDo) UpdateByPK(ctx context.Context, model *AssetSnapshots) error {
	builder := squirrel.Update(d.table).
		PlaceholderFormat(squirrel.Dollar)
	builder = builder.Set("exchange", model.Exchange)
	builder = builder.Set("total_balance", model.TotalBalance)
	builder = builder.Set("available_balance", model.AvailableBalance)
	builder = builder.Set("frozen_balance", model.FrozenBalance)
	builder = builder.Set("snapshot_time", model.SnapshotTime)
	builder = builder.Where(squirrel.Eq{
		"id": model.ID,
	})

	query, args, err := builder.ToSql()
	if err != nil {
		return fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("get rows affected: %w", err)
	}
	if affected == 0 {
		return ErrRecordNotFound
	}
	return nil
}

// DeleteByPK deletes a record by primary key
func (d *assetSnapshotsDo) DeleteByPK(ctx context.Context, iD int64) error {
	builder := squirrel.Delete(d.table).
		PlaceholderFormat(squirrel.Dollar).
		Where(squirrel.Eq{
			"id": iD,
		})

	query, args, err := builder.ToSql()
	if err != nil {
		return fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return fmt.Errorf("delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("get rows affected: %w", err)
	}
	if affected == 0 {
		return ErrRecordNotFound
	}
	return nil
}

// Upsert inserts or updates a record (uses ON CONFLICT for PostgreSQL)
// Only updates non-zero fields on conflict
func (d *assetSnapshotsDo) Upsert(ctx context.Context, model *AssetSnapshots) (*AssetSnapshots, error) {
	builder := squirrel.Insert(d.table).
		PlaceholderFormat(squirrel.Dollar).
		Columns("exchange", "total_balance", "available_balance", "frozen_balance", "snapshot_time").
		Values(model.Exchange, model.TotalBalance, model.AvailableBalance, model.FrozenBalance, model.SnapshotTime)

	// Build update clause for conflict resolution
	updateClause := "ON CONFLICT (id) DO UPDATE SET "
	updateClause += "exchange = CASE WHEN EXCLUDED.exchange = '' THEN asset_snapshots.exchange ELSE EXCLUDED.exchange END"
	updateClause += ", "
	updateClause += "total_balance = EXCLUDED.total_balance"
	updateClause += ", "
	updateClause += "available_balance = EXCLUDED.available_balance"
	updateClause += ", "
	updateClause += "frozen_balance = EXCLUDED.frozen_balance"
	updateClause += ", "
	updateClause += "snapshot_time = EXCLUDED.snapshot_time"

	builder = builder.Suffix(updateClause + " RETURNING " + strings.Join(d.columns, ", "))
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build upsert query: %w", err)
	}

	var result AssetSnapshots
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.Exchange,
		&result.TotalBalance,
		&result.AvailableBalance,
		&result.FrozenBalance,
		&result.SnapshotTime,
	)
	if err != nil {
		return nil, fmt.Errorf("upsert: %w", err)
	}
	return &result, nil
}

// UpsertAll inserts or updates a record, updating all fields on conflict
func (d *assetSnapshotsDo) UpsertAll(ctx context.Context, model *AssetSnapshots) (*AssetSnapshots, error) {
	builder := squirrel.Insert(d.table).
		PlaceholderFormat(squirrel.Dollar).
		Columns("exchange", "total_balance", "available_balance", "frozen_balance", "snapshot_time").
		Values(model.Exchange, model.TotalBalance, model.AvailableBalance, model.FrozenBalance, model.SnapshotTime)

	updateClause := "ON CONFLICT (id) DO UPDATE SET "
	updateClause += "exchange = EXCLUDED.exchange"
	updateClause += ", "
	updateClause += "total_balance = EXCLUDED.total_balance"
	updateClause += ", "
	updateClause += "available_balance = EXCLUDED.available_balance"
	updateClause += ", "
	updateClause += "frozen_balance = EXCLUDED.frozen_balance"
	updateClause += ", "
	updateClause += "snapshot_time = EXCLUDED.snapshot_time"

	builder = builder.Suffix(updateClause + " RETURNING " + strings.Join(d.columns, ", "))
	query, args, err := builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build upsert all query: %w", err)
	}

	var result AssetSnapshots
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.Exchange,
		&result.TotalBalance,
		&result.AvailableBalance,
		&result.FrozenBalance,
		&result.SnapshotTime,
	)
	if err != nil {
		return nil, fmt.Errorf("upsert all: %w", err)
	}
	return &result, nil
}

// FindByIndex performs a covering index query using only indexed columns.
// Automatically builds WHERE conditions for non-zero fields in the request.
// Returns only indexed columns to enable index-only scans (no table access).
func (d *assetSnapshotsDo) FindByIndex(ctx context.Context, req *AssetSnapshotsIndex) ([]*AssetSnapshotsIndex, error) {
	builder := squirrel.Select().
		From(d.table).
		PlaceholderFormat(squirrel.Dollar)

	// Auto-build WHERE conditions from non-zero fields
	if req.ID != 0 {
		builder = builder.Where(squirrel.Eq{"id": req.ID})
	}

	// Select only indexed columns (enables covering index scan)
	builder = builder.Columns("id")

	query, args, err := builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find by index query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find by index: %w", err)
	}
	defer rows.Close()

	var results []*AssetSnapshotsIndex
	for rows.Next() {
		var result AssetSnapshotsIndex
		err := rows.Scan(
			&result.ID,
		)
		if err != nil {
			return nil, fmt.Errorf("scan index result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}
