// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/Masterminds/squirrel"
)

// auditLogs is the query entry point for AuditLogs
var auditLogs = newAuditLogsQuery()

// newAuditLogsQuery creates a new query builder for AuditLogs
func newAuditLogsQuery() *auditLogsQuery {
	return &auditLogsQuery{
		fieldMap: map[string]Field{
			"id":          auditLogsField.ID,
			"user_id":     auditLogsField.UserID,
			"ip_address":  auditLogsField.IpAddress,
			"action":      auditLogsField.Action,
			"target_type": auditLogsField.TargetType,
			"target_id":   auditLogsField.TargetID,
			"changes":     auditLogsField.Changes,
			"is_verified": auditLogsField.IsVerified,
			"created_at":  auditLogsField.CreatedAt,
		},
	}
}

// auditLogsQuery is the query builder for AuditLogs
type auditLogsQuery struct {
	db       Executor
	fieldMap map[string]Field
}

// auditLogsField provides type-safe field access for AuditLogs
var auditLogsField = struct {
	ID         Int64Field
	UserID     Int64Field
	IpAddress  StringField
	Action     StringField
	TargetType StringField
	TargetID   StringField
	Changes    StringField
	IsVerified BoolField
	CreatedAt  TimeField
}{
	ID:         Int64Field("id"),
	UserID:     Int64Field("user_id"),
	IpAddress:  StringField("ip_address"),
	Action:     StringField("action"),
	TargetType: StringField("target_type"),
	TargetID:   StringField("target_id"),
	Changes:    StringField("changes"),
	IsVerified: BoolField("is_verified"),
	CreatedAt:  TimeField("created_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *auditLogsQuery) WithDB(db Executor) IAuditLogsDo {
	return &auditLogsDo{
		db:    db,
		table: "\"public\".\"audit_logs\"",
		columns: []string{
			"id",
			"user_id",
			"ip_address",
			"action",
			"target_type",
			"target_id",
			"changes",
			"is_verified",
			"created_at",
		},
	}
}

// As creates a table alias for the query
func (q *auditLogsQuery) As(alias string) *auditLogsQuery {
	return q
}

// IAuditLogsDo defines the interface for AuditLogs data operations
type IAuditLogsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *AuditLogs) (*AuditLogs, error)
	BatchCreate(ctx context.Context, models []*AuditLogs) ([]*AuditLogs, error)
	FindByPK(ctx context.Context, iD int64) (*AuditLogs, error)
	FindByIndex(ctx context.Context, req *AuditLogsIndex) ([]*AuditLogsIndex, error)
	UpdateByPK(ctx context.Context, model *AuditLogs) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *AuditLogs) (*AuditLogs, error)
	UpsertAll(ctx context.Context, model *AuditLogs) (*AuditLogs, error)

	// Query builder (type-safe, only accepts fields from this table)
	Where(conds ...WhereCondition) IAuditLogsDo
	Select(fields ...Field) IAuditLogsDo
	Order(orderBys ...OrderByClause) IAuditLogsDo
	Limit(limit int) IAuditLogsDo
	Offset(offset int) IAuditLogsDo

	// Execution methods
	Find(ctx context.Context) ([]*AuditLogs, error)
	First(ctx context.Context) (*AuditLogs, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IAuditLogsDo
}

// Ensure auditLogsDo implements IAuditLogsDo
var _ IAuditLogsDo = (*auditLogsDo)(nil)

// auditLogsDo wraps the query builder with chainable methods
type auditLogsDo struct {
	db      Executor
	table   string
	columns []string
	builder squirrel.SelectBuilder

	// Query state
	whereSet  bool
	selectSet bool
	orderSet  bool
	limitSet  bool
	offsetSet bool
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *auditLogsDo) WithDB(db Executor) IAuditLogsDo {
	return &auditLogsDo{
		db:      db,
		table:   d.table,
		columns: d.columns,
	}
}

// Where adds WHERE conditions (chainable)
func (d *auditLogsDo) Where(conds ...WhereCondition) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		d.builder = d.builder.Where(cond.ToSqlizer())
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *auditLogsDo) Select(fields ...Field) IAuditLogsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., auditLogsField.Age.Desc())
func (d *auditLogsDo) Order(orderBys ...OrderByClause) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *auditLogsDo) Limit(limit int) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *auditLogsDo) Offset(offset int) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *auditLogsDo) Find(ctx context.Context) ([]*AuditLogs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	defer rows.Close()

	var results []*AuditLogs
	for rows.Next() {
		var result AuditLogs
		err := rows.Scan(
			&result.ID,
			&result.UserID,
			&result.IpAddress,
			&result.Action,
			&result.TargetType,
			&result.TargetID,
			&result.Changes,
			&result.IsVerified,
			&result.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// First executes the query and returns the first matching record
func (d *auditLogsDo) First(ctx context.Context) (*AuditLogs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result AuditLogs
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.UserID,
		&result.IpAddress,
		&result.Action,
		&result.TargetType,
		&result.TargetID,
		&result.Changes,
		&result.IsVerified,
		&result.CreatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *auditLogsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.table).PlaceholderFormat(squirrel.Dollar)

	if d.whereSet {
		// Extract WHERE clauses from existing builder if any
		query, args, err := d.builder.ToSql()
		if err != nil {
			return 0, fmt.Errorf("build count query: %w", err)
		}
		// Parse WHERE clause from the query
		_ = query // TODO: extract WHERE clause properly
		_ = args
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowContext(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *auditLogsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *auditLogsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
