// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-19T18:09:36Z
// version: 1.0.0

package query

import (
	"context"
	"fmt"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

// auditLogs is the query entry point for AuditLogs
var auditLogs = newAuditLogsQuery()

// Default table alias for AuditLogs (used in JOINs)
const AuditLogsAlias = "auditLogs"

// newAuditLogsQuery creates a new query builder for AuditLogs
func newAuditLogsQuery() *auditLogsQuery {
	return &auditLogsQuery{
		fieldMap: map[string]Field{
			"id":          auditLogsField.ID,
			"user_id":     auditLogsField.UserID,
			"ip_address":  auditLogsField.IpAddress,
			"action":      auditLogsField.Action,
			"target_type": auditLogsField.TargetType,
			"target_id":   auditLogsField.TargetID,
			"changes":     auditLogsField.Changes,
			"is_verified": auditLogsField.IsVerified,
			"created_at":  auditLogsField.CreatedAt,
		},
		defaultAlias: AuditLogsAlias,
	}
}

// auditLogsQuery is the query builder for AuditLogs
type auditLogsQuery struct {
	db           Executor
	fieldMap     map[string]Field
	defaultAlias string
}

// auditLogsField provides type-safe field access for AuditLogs
var auditLogsField = struct {
	ID         Int64Field
	UserID     Int64Field
	IpAddress  StringField
	Action     StringField
	TargetType StringField
	TargetID   StringField
	Changes    StringField
	IsVerified BoolField
	CreatedAt  TimeField
}{
	ID:         Int64Field("id"),
	UserID:     Int64Field("user_id"),
	IpAddress:  StringField("ip_address"),
	Action:     StringField("action"),
	TargetType: StringField("target_type"),
	TargetID:   StringField("target_id"),
	Changes:    StringField("changes"),
	IsVerified: BoolField("is_verified"),
	CreatedAt:  TimeField("created_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *auditLogsQuery) WithDB(db Executor) IAuditLogsDo {
	return &auditLogsDo{
		db:           db,
		table:        "\"public\".\"audit_logs\"",
		alias:        q.defaultAlias, // 使用默认别名
		defaultAlias: q.defaultAlias,
		columns: []string{
			"id",
			"user_id",
			"ip_address",
			"action",
			"target_type",
			"target_id",
			"changes",
			"is_verified",
			"created_at",
		},
		Field: &auditLogsField,
	}
}

// IAuditLogsDo defines the interface for AuditLogs data operations
type IAuditLogsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *AuditLogs) (*AuditLogs, error)
	BatchCreate(ctx context.Context, models []*AuditLogs) ([]*AuditLogs, error)
	FindByPK(ctx context.Context, iD int64) (*AuditLogs, error)
	FindByIndex(ctx context.Context, req *AuditLogsIndex) ([]*AuditLogsIndex, error)
	UpdateByPK(ctx context.Context, model *AuditLogs) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *AuditLogs) (*AuditLogs, error)
	UpsertAll(ctx context.Context, model *AuditLogs) (*AuditLogs, error)

	// Query builder (type-safe, only accepts fields from this table)
	As(alias string) IAuditLogsDo
	Where(conds ...WhereCondition) IAuditLogsDo
	Select(fields ...Field) IAuditLogsDo
	SelectAgg(aggs ...AggregateFunc) IAuditLogsDo
	Distinct() IAuditLogsDo
	GroupBy(fields ...Field) IAuditLogsDo
	Having(cond squirrel.Sqlizer) IAuditLogsDo
	Order(orderBys ...OrderByClause) IAuditLogsDo
	Limit(limit int) IAuditLogsDo
	Offset(offset int) IAuditLogsDo

	// Execution methods
	Find(ctx context.Context) ([]*AuditLogs, error)
	First(ctx context.Context) (*AuditLogs, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IAuditLogsDo
}

// Ensure auditLogsDo implements IAuditLogsDo
var _ IAuditLogsDo = (*auditLogsDo)(nil)

// auditLogsDo wraps the query builder with chainable methods
type auditLogsDo struct {
	db           Executor
	table        string
	alias        string // 自定义别名（通过 As() 设置）
	defaultAlias string // 默认别名（模型名）
	columns      []string
	builder      squirrel.SelectBuilder

	// Field provides type-safe field access for this model
	Field *struct {
		ID         Int64Field
		UserID     Int64Field
		IpAddress  StringField
		Action     StringField
		TargetType StringField
		TargetID   StringField
		Changes    StringField
		IsVerified BoolField
		CreatedAt  TimeField
	}

	// Query state
	whereSet    bool
	selectSet   bool
	distinctSet bool
	groupBySet  bool
	havingSet   bool
	orderSet    bool
	limitSet    bool
	offsetSet   bool

	// Store GROUP BY fields
	groupByFields []Field

	// Store aggregate functions for SELECT
	aggFuncs []AggregateFunc

	// Store WHERE conditions for reuse in Update/Delete
	whereConds []squirrel.Sqlizer
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *auditLogsDo) WithDB(db Executor) IAuditLogsDo {
	return &auditLogsDo{
		db:            db,
		table:         d.table,
		alias:         d.alias,
		defaultAlias:  d.defaultAlias,
		columns:       d.columns,
		builder:       d.builder,
		Field:         d.Field,
		whereSet:      d.whereSet,
		selectSet:     d.selectSet,
		distinctSet:   d.distinctSet,
		groupBySet:    d.groupBySet,
		havingSet:     d.havingSet,
		orderSet:      d.orderSet,
		limitSet:      d.limitSet,
		offsetSet:     d.offsetSet,
		whereConds:    d.whereConds,
		groupByFields: d.groupByFields,
		aggFuncs:      d.aggFuncs,
	}
}

// As sets a custom table alias for the query
// This is OPTIONAL - a default alias is already set automatically
// Use this only when you need a different alias (e.g., self-join)
// Example: query.user.WithDB(db).As("u1") for self-join scenarios
func (d *auditLogsDo) As(alias string) IAuditLogsDo {
	newDo := *d
	newDo.alias = alias
	newDo.Field = d.Field
	return &newDo
}

// getTableExpr returns the table expression with alias
// Always uses an alias (either custom via As() or default)
func (d *auditLogsDo) getTableExpr() string {
	alias := d.alias
	if alias == "" {
		alias = d.defaultAlias
	}
	return d.table + " AS " + alias
}

// Where adds WHERE conditions (chainable)
func (d *auditLogsDo) Where(conds ...WhereCondition) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		sqlizer := cond.ToSqlizer()
		d.builder = d.builder.Where(sqlizer)
		d.whereConds = append(d.whereConds, sqlizer)
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *auditLogsDo) Select(fields ...Field) IAuditLogsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Distinct adds DISTINCT to the query (chainable)
// Example: query.user.WithDB(db).Select(userField.Email).Distinct().Find(ctx)
func (d *auditLogsDo) Distinct() IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Distinct()
	d.distinctSet = true
	return d
}

// SelectAgg selects aggregate functions (chainable)
// Example: query.order.WithDB(db).SelectAgg(orderField.Amount.Sum().As("total"), orderField.ID.Count().As("count"))
func (d *auditLogsDo) SelectAgg(aggs ...AggregateFunc) IAuditLogsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}

	cols := make([]string, len(aggs))
	for i, agg := range aggs {
		cols[i] = agg.ToSQL()
	}
	d.builder = d.builder.Columns(cols...)
	d.aggFuncs = append(d.aggFuncs, aggs...)
	return d
}

// GroupBy adds GROUP BY clause (chainable)
// Example: query.order.WithDB(db).Select(orderField.UserID).SelectAgg(orderField.Amount.Sum()).GroupBy(orderField.UserID)
func (d *auditLogsDo) GroupBy(fields ...Field) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.GroupBy(cols...)
	d.groupBySet = true
	d.groupByFields = append(d.groupByFields, fields...)
	return d
}

// Having adds HAVING clause (chainable, used with GROUP BY)
// Example: query.order.WithDB(db).GroupBy(orderField.UserID).Having(squirrel.Gt{"SUM(amount)": 1000})
func (d *auditLogsDo) Having(cond squirrel.Sqlizer) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Having(cond)
	d.havingSet = true
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., auditLogsField.Age.Desc())
func (d *auditLogsDo) Order(orderBys ...OrderByClause) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *auditLogsDo) Limit(limit int) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *auditLogsDo) Offset(offset int) IAuditLogsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *auditLogsDo) Find(ctx context.Context) ([]*AuditLogs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}
	var results []*AuditLogs
	err = d.db.QueryRowsCtx(ctx, &results, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	return results, nil
}

// First executes the query and returns the first matching record
func (d *auditLogsDo) First(ctx context.Context) (*AuditLogs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result AuditLogs
	err = d.db.QueryRowCtx(ctx, &result, query, args...)
	if err == sqlx.ErrNotFound {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *auditLogsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		countBuilder = countBuilder.Where(cond)
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowCtx(ctx, &count, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *auditLogsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *auditLogsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
