// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-19T17:23:17Z
// version: 1.0.0

package query

import (
	"context"
	"fmt"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

// exchangeAccounts is the query entry point for ExchangeAccounts
var exchangeAccounts = newExchangeAccountsQuery()

// Default table alias for ExchangeAccounts (used in JOINs)
const ExchangeAccountsAlias = "exchangeAccounts"

// newExchangeAccountsQuery creates a new query builder for ExchangeAccounts
func newExchangeAccountsQuery() *exchangeAccountsQuery {
	return &exchangeAccountsQuery{
		fieldMap: map[string]Field{
			"id":                   exchangeAccountsField.ID,
			"user_id":              exchangeAccountsField.UserID,
			"label":                exchangeAccountsField.Label,
			"exchange":             exchangeAccountsField.Exchange,
			"api_key":              exchangeAccountsField.ApiKey,
			"encrypted_api_secret": exchangeAccountsField.EncryptedApiSecret,
			"encrypted_passphrase": exchangeAccountsField.EncryptedPassphrase,
			"config":               exchangeAccountsField.Config,
			"is_active":            exchangeAccountsField.IsActive,
			"created_at":           exchangeAccountsField.CreatedAt,
			"updated_at":           exchangeAccountsField.UpdatedAt,
		},
		defaultAlias: ExchangeAccountsAlias,
	}
}

// exchangeAccountsQuery is the query builder for ExchangeAccounts
type exchangeAccountsQuery struct {
	db           Executor
	fieldMap     map[string]Field
	defaultAlias string
}

// exchangeAccountsField provides type-safe field access for ExchangeAccounts
var exchangeAccountsField = struct {
	ID                  Int64Field
	UserID              Int64Field
	Label               StringField
	Exchange            StringField
	ApiKey              StringField
	EncryptedApiSecret  StringField
	EncryptedPassphrase StringField
	Config              StringField
	IsActive            BoolField
	CreatedAt           TimeField
	UpdatedAt           TimeField
}{
	ID:                  Int64Field("id"),
	UserID:              Int64Field("user_id"),
	Label:               StringField("label"),
	Exchange:            StringField("exchange"),
	ApiKey:              StringField("api_key"),
	EncryptedApiSecret:  StringField("encrypted_api_secret"),
	EncryptedPassphrase: StringField("encrypted_passphrase"),
	Config:              StringField("config"),
	IsActive:            BoolField("is_active"),
	CreatedAt:           TimeField("created_at"),
	UpdatedAt:           TimeField("updated_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *exchangeAccountsQuery) WithDB(db Executor) IExchangeAccountsDo {
	return &exchangeAccountsDo{
		db:           db,
		table:        "\"public\".\"exchange_accounts\"",
		alias:        q.defaultAlias, // 使用默认别名
		defaultAlias: q.defaultAlias,
		columns: []string{
			"id",
			"user_id",
			"label",
			"exchange",
			"api_key",
			"encrypted_api_secret",
			"encrypted_passphrase",
			"config",
			"is_active",
			"created_at",
			"updated_at",
		},
		Field: &exchangeAccountsField,
	}
}

// IExchangeAccountsDo defines the interface for ExchangeAccounts data operations
type IExchangeAccountsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *ExchangeAccounts) (*ExchangeAccounts, error)
	BatchCreate(ctx context.Context, models []*ExchangeAccounts) ([]*ExchangeAccounts, error)
	FindByPK(ctx context.Context, iD int64) (*ExchangeAccounts, error)
	FindByIndex(ctx context.Context, req *ExchangeAccountsIndex) ([]*ExchangeAccountsIndex, error)
	UpdateByPK(ctx context.Context, model *ExchangeAccounts) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *ExchangeAccounts) (*ExchangeAccounts, error)
	UpsertAll(ctx context.Context, model *ExchangeAccounts) (*ExchangeAccounts, error)

	// Query builder (type-safe, only accepts fields from this table)
	As(alias string) IExchangeAccountsDo
	Where(conds ...WhereCondition) IExchangeAccountsDo
	Select(fields ...Field) IExchangeAccountsDo
	SelectAgg(aggs ...AggregateFunc) IExchangeAccountsDo
	Distinct() IExchangeAccountsDo
	GroupBy(fields ...Field) IExchangeAccountsDo
	Having(cond squirrel.Sqlizer) IExchangeAccountsDo
	Order(orderBys ...OrderByClause) IExchangeAccountsDo
	Limit(limit int) IExchangeAccountsDo
	Offset(offset int) IExchangeAccountsDo

	// Execution methods
	Find(ctx context.Context) ([]*ExchangeAccounts, error)
	First(ctx context.Context) (*ExchangeAccounts, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IExchangeAccountsDo
}

// Ensure exchangeAccountsDo implements IExchangeAccountsDo
var _ IExchangeAccountsDo = (*exchangeAccountsDo)(nil)

// exchangeAccountsDo wraps the query builder with chainable methods
type exchangeAccountsDo struct {
	db           Executor
	table        string
	alias        string // 自定义别名（通过 As() 设置）
	defaultAlias string // 默认别名（模型名）
	columns      []string
	builder      squirrel.SelectBuilder

	// Field provides type-safe field access for this model
	Field *struct {
		ID                  Int64Field
		UserID              Int64Field
		Label               StringField
		Exchange            StringField
		ApiKey              StringField
		EncryptedApiSecret  StringField
		EncryptedPassphrase StringField
		Config              StringField
		IsActive            BoolField
		CreatedAt           TimeField
		UpdatedAt           TimeField
	}

	// Query state
	whereSet    bool
	selectSet   bool
	distinctSet bool
	groupBySet  bool
	havingSet   bool
	orderSet    bool
	limitSet    bool
	offsetSet   bool

	// Store GROUP BY fields
	groupByFields []Field

	// Store aggregate functions for SELECT
	aggFuncs []AggregateFunc

	// Store WHERE conditions for reuse in Update/Delete
	whereConds []squirrel.Sqlizer
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *exchangeAccountsDo) WithDB(db Executor) IExchangeAccountsDo {
	return &exchangeAccountsDo{
		db:            db,
		table:         d.table,
		alias:         d.alias,
		defaultAlias:  d.defaultAlias,
		columns:       d.columns,
		builder:       d.builder,
		Field:         d.Field,
		whereSet:      d.whereSet,
		selectSet:     d.selectSet,
		distinctSet:   d.distinctSet,
		groupBySet:    d.groupBySet,
		havingSet:     d.havingSet,
		orderSet:      d.orderSet,
		limitSet:      d.limitSet,
		offsetSet:     d.offsetSet,
		whereConds:    d.whereConds,
		groupByFields: d.groupByFields,
		aggFuncs:      d.aggFuncs,
	}
}

// As sets a custom table alias for the query
// This is OPTIONAL - a default alias is already set automatically
// Use this only when you need a different alias (e.g., self-join)
// Example: query.user.WithDB(db).As("u1") for self-join scenarios
func (d *exchangeAccountsDo) As(alias string) IExchangeAccountsDo {
	newDo := *d
	newDo.alias = alias
	newDo.Field = d.Field
	return &newDo
}

// getTableExpr returns the table expression with alias
// Always uses an alias (either custom via As() or default)
func (d *exchangeAccountsDo) getTableExpr() string {
	alias := d.alias
	if alias == "" {
		alias = d.defaultAlias
	}
	return d.table + " AS " + alias
}

// Where adds WHERE conditions (chainable)
func (d *exchangeAccountsDo) Where(conds ...WhereCondition) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		sqlizer := cond.ToSqlizer()
		d.builder = d.builder.Where(sqlizer)
		d.whereConds = append(d.whereConds, sqlizer)
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *exchangeAccountsDo) Select(fields ...Field) IExchangeAccountsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Distinct adds DISTINCT to the query (chainable)
// Example: query.user.WithDB(db).Select(userField.Email).Distinct().Find(ctx)
func (d *exchangeAccountsDo) Distinct() IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Distinct()
	d.distinctSet = true
	return d
}

// SelectAgg selects aggregate functions (chainable)
// Example: query.order.WithDB(db).SelectAgg(orderField.Amount.Sum().As("total"), orderField.ID.Count().As("count"))
func (d *exchangeAccountsDo) SelectAgg(aggs ...AggregateFunc) IExchangeAccountsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}

	cols := make([]string, len(aggs))
	for i, agg := range aggs {
		cols[i] = agg.ToSQL()
	}
	d.builder = d.builder.Columns(cols...)
	d.aggFuncs = append(d.aggFuncs, aggs...)
	return d
}

// GroupBy adds GROUP BY clause (chainable)
// Example: query.order.WithDB(db).Select(orderField.UserID).SelectAgg(orderField.Amount.Sum()).GroupBy(orderField.UserID)
func (d *exchangeAccountsDo) GroupBy(fields ...Field) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.GroupBy(cols...)
	d.groupBySet = true
	d.groupByFields = append(d.groupByFields, fields...)
	return d
}

// Having adds HAVING clause (chainable, used with GROUP BY)
// Example: query.order.WithDB(db).GroupBy(orderField.UserID).Having(squirrel.Gt{"SUM(amount)": 1000})
func (d *exchangeAccountsDo) Having(cond squirrel.Sqlizer) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Having(cond)
	d.havingSet = true
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., exchangeAccountsField.Age.Desc())
func (d *exchangeAccountsDo) Order(orderBys ...OrderByClause) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *exchangeAccountsDo) Limit(limit int) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *exchangeAccountsDo) Offset(offset int) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *exchangeAccountsDo) Find(ctx context.Context) ([]*ExchangeAccounts, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}
	var results []*ExchangeAccounts
	err = d.db.QueryRowsCtx(ctx, &results, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	return results, nil
}

// First executes the query and returns the first matching record
func (d *exchangeAccountsDo) First(ctx context.Context) (*ExchangeAccounts, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result ExchangeAccounts
	err = d.db.QueryRowCtx(ctx, &result, query, args...)
	if err == sqlx.ErrNotFound {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *exchangeAccountsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		countBuilder = countBuilder.Where(cond)
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowCtx(ctx, &count, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *exchangeAccountsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *exchangeAccountsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
