// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/Masterminds/squirrel"
)

// exchangeAccounts is the query entry point for ExchangeAccounts
var exchangeAccounts = newExchangeAccountsQuery()

// newExchangeAccountsQuery creates a new query builder for ExchangeAccounts
func newExchangeAccountsQuery() *exchangeAccountsQuery {
	return &exchangeAccountsQuery{
		fieldMap: map[string]Field{
			"id":                   exchangeAccountsField.ID,
			"user_id":              exchangeAccountsField.UserID,
			"label":                exchangeAccountsField.Label,
			"exchange":             exchangeAccountsField.Exchange,
			"api_key":              exchangeAccountsField.ApiKey,
			"encrypted_api_secret": exchangeAccountsField.EncryptedApiSecret,
			"encrypted_passphrase": exchangeAccountsField.EncryptedPassphrase,
			"config":               exchangeAccountsField.Config,
			"is_active":            exchangeAccountsField.IsActive,
			"created_at":           exchangeAccountsField.CreatedAt,
			"updated_at":           exchangeAccountsField.UpdatedAt,
		},
	}
}

// exchangeAccountsQuery is the query builder for ExchangeAccounts
type exchangeAccountsQuery struct {
	db       Executor
	fieldMap map[string]Field
}

// exchangeAccountsField provides type-safe field access for ExchangeAccounts
var exchangeAccountsField = struct {
	ID                  Int64Field
	UserID              Int64Field
	Label               StringField
	Exchange            StringField
	ApiKey              StringField
	EncryptedApiSecret  StringField
	EncryptedPassphrase StringField
	Config              StringField
	IsActive            BoolField
	CreatedAt           TimeField
	UpdatedAt           TimeField
}{
	ID:                  Int64Field("id"),
	UserID:              Int64Field("user_id"),
	Label:               StringField("label"),
	Exchange:            StringField("exchange"),
	ApiKey:              StringField("api_key"),
	EncryptedApiSecret:  StringField("encrypted_api_secret"),
	EncryptedPassphrase: StringField("encrypted_passphrase"),
	Config:              StringField("config"),
	IsActive:            BoolField("is_active"),
	CreatedAt:           TimeField("created_at"),
	UpdatedAt:           TimeField("updated_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *exchangeAccountsQuery) WithDB(db Executor) IExchangeAccountsDo {
	return &exchangeAccountsDo{
		db:    db,
		table: "\"public\".\"exchange_accounts\"",
		columns: []string{
			"id",
			"user_id",
			"label",
			"exchange",
			"api_key",
			"encrypted_api_secret",
			"encrypted_passphrase",
			"config",
			"is_active",
			"created_at",
			"updated_at",
		},
	}
}

// As creates a table alias for the query
func (q *exchangeAccountsQuery) As(alias string) *exchangeAccountsQuery {
	return q
}

// IExchangeAccountsDo defines the interface for ExchangeAccounts data operations
type IExchangeAccountsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *ExchangeAccounts) (*ExchangeAccounts, error)
	BatchCreate(ctx context.Context, models []*ExchangeAccounts) ([]*ExchangeAccounts, error)
	FindByPK(ctx context.Context, iD int64) (*ExchangeAccounts, error)
	FindByIndex(ctx context.Context, req *ExchangeAccountsIndex) ([]*ExchangeAccountsIndex, error)
	UpdateByPK(ctx context.Context, model *ExchangeAccounts) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *ExchangeAccounts) (*ExchangeAccounts, error)
	UpsertAll(ctx context.Context, model *ExchangeAccounts) (*ExchangeAccounts, error)

	// Query builder (type-safe, only accepts fields from this table)
	Where(conds ...WhereCondition) IExchangeAccountsDo
	Select(fields ...Field) IExchangeAccountsDo
	Order(orderBys ...OrderByClause) IExchangeAccountsDo
	Limit(limit int) IExchangeAccountsDo
	Offset(offset int) IExchangeAccountsDo

	// Execution methods
	Find(ctx context.Context) ([]*ExchangeAccounts, error)
	First(ctx context.Context) (*ExchangeAccounts, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IExchangeAccountsDo
}

// Ensure exchangeAccountsDo implements IExchangeAccountsDo
var _ IExchangeAccountsDo = (*exchangeAccountsDo)(nil)

// exchangeAccountsDo wraps the query builder with chainable methods
type exchangeAccountsDo struct {
	db      Executor
	table   string
	columns []string
	builder squirrel.SelectBuilder

	// Query state
	whereSet  bool
	selectSet bool
	orderSet  bool
	limitSet  bool
	offsetSet bool
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *exchangeAccountsDo) WithDB(db Executor) IExchangeAccountsDo {
	return &exchangeAccountsDo{
		db:      db,
		table:   d.table,
		columns: d.columns,
	}
}

// Where adds WHERE conditions (chainable)
func (d *exchangeAccountsDo) Where(conds ...WhereCondition) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		d.builder = d.builder.Where(cond.ToSqlizer())
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *exchangeAccountsDo) Select(fields ...Field) IExchangeAccountsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., exchangeAccountsField.Age.Desc())
func (d *exchangeAccountsDo) Order(orderBys ...OrderByClause) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *exchangeAccountsDo) Limit(limit int) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *exchangeAccountsDo) Offset(offset int) IExchangeAccountsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *exchangeAccountsDo) Find(ctx context.Context) ([]*ExchangeAccounts, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	defer rows.Close()

	var results []*ExchangeAccounts
	for rows.Next() {
		var result ExchangeAccounts
		err := rows.Scan(
			&result.ID,
			&result.UserID,
			&result.Label,
			&result.Exchange,
			&result.ApiKey,
			&result.EncryptedApiSecret,
			&result.EncryptedPassphrase,
			&result.Config,
			&result.IsActive,
			&result.CreatedAt,
			&result.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// First executes the query and returns the first matching record
func (d *exchangeAccountsDo) First(ctx context.Context) (*ExchangeAccounts, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result ExchangeAccounts
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.UserID,
		&result.Label,
		&result.Exchange,
		&result.ApiKey,
		&result.EncryptedApiSecret,
		&result.EncryptedPassphrase,
		&result.Config,
		&result.IsActive,
		&result.CreatedAt,
		&result.UpdatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *exchangeAccountsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.table).PlaceholderFormat(squirrel.Dollar)

	if d.whereSet {
		// Extract WHERE clauses from existing builder if any
		query, args, err := d.builder.ToSql()
		if err != nil {
			return 0, fmt.Errorf("build count query: %w", err)
		}
		// Parse WHERE clause from the query
		_ = query // TODO: extract WHERE clause properly
		_ = args
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowContext(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *exchangeAccountsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *exchangeAccountsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
