// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/Masterminds/squirrel"
)

// executions is the query entry point for Executions
var executions = newExecutionsQuery()

// newExecutionsQuery creates a new query builder for Executions
func newExecutionsQuery() *executionsQuery {
	return &executionsQuery{
		fieldMap: map[string]Field{
			"id":         executionsField.ID,
			"order_id":   executionsField.OrderID,
			"client_oid": executionsField.ClientOid,
			"exec_id":    executionsField.ExecID,
			"symbol":     executionsField.Symbol,
			"side":       executionsField.Side,
			"price":      executionsField.Price,
			"quantity":   executionsField.Quantity,
			"quote_qty":  executionsField.QuoteQty,
			"fee":        executionsField.Fee,
			"fee_asset":  executionsField.FeeAsset,
			"traded_at":  executionsField.TradedAt,
			"created_at": executionsField.CreatedAt,
		},
	}
}

// executionsQuery is the query builder for Executions
type executionsQuery struct {
	db       Executor
	fieldMap map[string]Field
}

// executionsField provides type-safe field access for Executions
var executionsField = struct {
	ID        Int64Field
	OrderID   Int64Field
	ClientOid StringField
	ExecID    StringField
	Symbol    StringField
	Side      StringField
	Price     DecimalField
	Quantity  DecimalField
	QuoteQty  DecimalField
	Fee       DecimalField
	FeeAsset  StringField
	TradedAt  TimeField
	CreatedAt TimeField
}{
	ID:        Int64Field("id"),
	OrderID:   Int64Field("order_id"),
	ClientOid: StringField("client_oid"),
	ExecID:    StringField("exec_id"),
	Symbol:    StringField("symbol"),
	Side:      StringField("side"),
	Price:     DecimalField("price"),
	Quantity:  DecimalField("quantity"),
	QuoteQty:  DecimalField("quote_qty"),
	Fee:       DecimalField("fee"),
	FeeAsset:  StringField("fee_asset"),
	TradedAt:  TimeField("traded_at"),
	CreatedAt: TimeField("created_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *executionsQuery) WithDB(db Executor) IExecutionsDo {
	return &executionsDo{
		db:    db,
		table: "\"public\".\"executions\"",
		columns: []string{
			"id",
			"order_id",
			"client_oid",
			"exec_id",
			"symbol",
			"side",
			"price",
			"quantity",
			"quote_qty",
			"fee",
			"fee_asset",
			"traded_at",
			"created_at",
		},
	}
}

// As creates a table alias for the query
func (q *executionsQuery) As(alias string) *executionsQuery {
	return q
}

// IExecutionsDo defines the interface for Executions data operations
type IExecutionsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *Executions) (*Executions, error)
	BatchCreate(ctx context.Context, models []*Executions) ([]*Executions, error)
	FindByPK(ctx context.Context, iD int64) (*Executions, error)
	FindByIndex(ctx context.Context, req *ExecutionsIndex) ([]*ExecutionsIndex, error)
	UpdateByPK(ctx context.Context, model *Executions) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *Executions) (*Executions, error)
	UpsertAll(ctx context.Context, model *Executions) (*Executions, error)

	// Query builder (type-safe, only accepts fields from this table)
	Where(conds ...WhereCondition) IExecutionsDo
	Select(fields ...Field) IExecutionsDo
	Order(orderBys ...OrderByClause) IExecutionsDo
	Limit(limit int) IExecutionsDo
	Offset(offset int) IExecutionsDo

	// Execution methods
	Find(ctx context.Context) ([]*Executions, error)
	First(ctx context.Context) (*Executions, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IExecutionsDo
}

// Ensure executionsDo implements IExecutionsDo
var _ IExecutionsDo = (*executionsDo)(nil)

// executionsDo wraps the query builder with chainable methods
type executionsDo struct {
	db      Executor
	table   string
	columns []string
	builder squirrel.SelectBuilder

	// Query state
	whereSet  bool
	selectSet bool
	orderSet  bool
	limitSet  bool
	offsetSet bool
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *executionsDo) WithDB(db Executor) IExecutionsDo {
	return &executionsDo{
		db:      db,
		table:   d.table,
		columns: d.columns,
	}
}

// Where adds WHERE conditions (chainable)
func (d *executionsDo) Where(conds ...WhereCondition) IExecutionsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		d.builder = d.builder.Where(cond.ToSqlizer())
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *executionsDo) Select(fields ...Field) IExecutionsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., executionsField.Age.Desc())
func (d *executionsDo) Order(orderBys ...OrderByClause) IExecutionsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *executionsDo) Limit(limit int) IExecutionsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *executionsDo) Offset(offset int) IExecutionsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *executionsDo) Find(ctx context.Context) ([]*Executions, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	defer rows.Close()

	var results []*Executions
	for rows.Next() {
		var result Executions
		err := rows.Scan(
			&result.ID,
			&result.OrderID,
			&result.ClientOid,
			&result.ExecID,
			&result.Symbol,
			&result.Side,
			&result.Price,
			&result.Quantity,
			&result.QuoteQty,
			&result.Fee,
			&result.FeeAsset,
			&result.TradedAt,
			&result.CreatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// First executes the query and returns the first matching record
func (d *executionsDo) First(ctx context.Context) (*Executions, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result Executions
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.OrderID,
		&result.ClientOid,
		&result.ExecID,
		&result.Symbol,
		&result.Side,
		&result.Price,
		&result.Quantity,
		&result.QuoteQty,
		&result.Fee,
		&result.FeeAsset,
		&result.TradedAt,
		&result.CreatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *executionsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.table).PlaceholderFormat(squirrel.Dollar)

	if d.whereSet {
		// Extract WHERE clauses from existing builder if any
		query, args, err := d.builder.ToSql()
		if err != nil {
			return 0, fmt.Errorf("build count query: %w", err)
		}
		// Parse WHERE clause from the query
		_ = query // TODO: extract WHERE clause properly
		_ = args
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowContext(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *executionsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *executionsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
