// Code generated by gpmg. DO NOT EDIT.

package query

import (
	"fmt"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/lib/pq"
	"github.com/shopspring/decimal"
)

// Field represents a table field with type-safe query methods
type Field interface {
	ColumnName() string
}

// OrderByClause represents an ORDER BY clause
type OrderByClause interface {
	ToSQL() string
}

// orderBy is the internal implementation of OrderByClause
type orderBy string

func (o orderBy) ToSQL() string {
	return string(o)
}

// GroupByClause represents a GROUP BY clause
type GroupByClause interface {
	ColumnName() string
}

// AggregateFunc represents an aggregate function (SUM, AVG, etc.)
type AggregateFunc struct {
	funcName string
	field    Field
	alias    string
}

func (a AggregateFunc) ColumnName() string {
	if a.alias != "" {
		return a.alias
	}
	return fmt.Sprintf("%s(%s)", a.funcName, a.field.ColumnName())
}

func (a AggregateFunc) As(alias string) AggregateFunc {
	a.alias = alias
	return a
}

func (a AggregateFunc) ToSQL() string {
	sql := fmt.Sprintf("%s(%s)", a.funcName, a.field.ColumnName())
	if a.alias != "" {
		sql += " AS " + a.alias
	}
	return sql
}

// HavingCondition represents a HAVING condition
type HavingCondition struct {
	sqlizer squirrel.Sqlizer
}

func (h HavingCondition) ToSqlizer() squirrel.Sqlizer {
	return h.sqlizer
}

// WhereCondition represents a type-safe WHERE condition
type WhereCondition interface {
	ToSqlizer() squirrel.Sqlizer
}

// whereCondition is the internal implementation of WhereCondition
type whereCondition struct {
	sqlizer squirrel.Sqlizer
}

func (w whereCondition) ToSqlizer() squirrel.Sqlizer {
	return w.sqlizer
}

// ===============================================
// Int64 Field
// ===============================================

type Int64Field string

func (f Int64Field) ColumnName() string            { return string(f) }
func (f Int64Field) Asc() OrderByClause            { return orderBy(string(f) + " ASC") }
func (f Int64Field) Desc() OrderByClause           { return orderBy(string(f) + " DESC") }
func (f Int64Field) AscNullsFirst() OrderByClause  { return orderBy(string(f) + " ASC NULLS FIRST") }
func (f Int64Field) AscNullsLast() OrderByClause   { return orderBy(string(f) + " ASC NULLS LAST") }
func (f Int64Field) DescNullsFirst() OrderByClause { return orderBy(string(f) + " DESC NULLS FIRST") }
func (f Int64Field) DescNullsLast() OrderByClause  { return orderBy(string(f) + " DESC NULLS LAST") }

// Eq generates field = value condition
func (f Int64Field) Eq(v int64) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

// Neq generates field <> value condition
func (f Int64Field) Neq(v int64) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

// Gt generates field > value condition
func (f Int64Field) Gt(v int64) WhereCondition {
	return whereCondition{squirrel.Gt{string(f): v}}
}

// Gte generates field >= value condition
func (f Int64Field) Gte(v int64) WhereCondition {
	return whereCondition{squirrel.GtOrEq{string(f): v}}
}

// Lt generates field < value condition
func (f Int64Field) Lt(v int64) WhereCondition {
	return whereCondition{squirrel.Lt{string(f): v}}
}

// Lte generates field <= value condition
func (f Int64Field) Lte(v int64) WhereCondition {
	return whereCondition{squirrel.LtOrEq{string(f): v}}
}

// In generates field IN (...values) condition
func (f Int64Field) In(values ...int64) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): values}}
}

// NotIn generates field NOT IN (...values) condition
func (f Int64Field) NotIn(values ...int64) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): values}}
}

// Between generates field BETWEEN min AND max condition
func (f Int64Field) Between(min, max int64) WhereCondition {
	return whereCondition{squirrel.And{
		squirrel.GtOrEq{string(f): min},
		squirrel.LtOrEq{string(f): max},
	}}
}

// Aggregate functions for Int64Field
func (f Int64Field) Sum() AggregateFunc {
	return AggregateFunc{funcName: "SUM", field: f}
}

func (f Int64Field) Avg() AggregateFunc {
	return AggregateFunc{funcName: "AVG", field: f}
}

func (f Int64Field) Max() AggregateFunc {
	return AggregateFunc{funcName: "MAX", field: f}
}

func (f Int64Field) Min() AggregateFunc {
	return AggregateFunc{funcName: "MIN", field: f}
}

func (f Int64Field) Count() AggregateFunc {
	return AggregateFunc{funcName: "COUNT", field: f}
}

// ===============================================
// Float64 Field
// ===============================================

type Float64Field string

func (f Float64Field) ColumnName() string            { return string(f) }
func (f Float64Field) Asc() OrderByClause            { return orderBy(string(f) + " ASC") }
func (f Float64Field) Desc() OrderByClause           { return orderBy(string(f) + " DESC") }
func (f Float64Field) AscNullsFirst() OrderByClause  { return orderBy(string(f) + " ASC NULLS FIRST") }
func (f Float64Field) AscNullsLast() OrderByClause   { return orderBy(string(f) + " ASC NULLS LAST") }
func (f Float64Field) DescNullsFirst() OrderByClause { return orderBy(string(f) + " DESC NULLS FIRST") }
func (f Float64Field) DescNullsLast() OrderByClause  { return orderBy(string(f) + " DESC NULLS LAST") }

func (f Float64Field) Eq(v float64) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f Float64Field) Neq(v float64) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

func (f Float64Field) Gt(v float64) WhereCondition {
	return whereCondition{squirrel.Gt{string(f): v}}
}

func (f Float64Field) Gte(v float64) WhereCondition {
	return whereCondition{squirrel.GtOrEq{string(f): v}}
}

func (f Float64Field) Lt(v float64) WhereCondition {
	return whereCondition{squirrel.Lt{string(f): v}}
}

func (f Float64Field) Lte(v float64) WhereCondition {
	return whereCondition{squirrel.LtOrEq{string(f): v}}
}

func (f Float64Field) In(values ...float64) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): values}}
}

func (f Float64Field) NotIn(values ...float64) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): values}}
}

func (f Float64Field) Between(min, max float64) WhereCondition {
	return whereCondition{squirrel.And{
		squirrel.GtOrEq{string(f): min},
		squirrel.LtOrEq{string(f): max},
	}}
}

// Aggregate functions for Float64Field
func (f Float64Field) Sum() AggregateFunc {
	return AggregateFunc{funcName: "SUM", field: f}
}

func (f Float64Field) Avg() AggregateFunc {
	return AggregateFunc{funcName: "AVG", field: f}
}

func (f Float64Field) Max() AggregateFunc {
	return AggregateFunc{funcName: "MAX", field: f}
}

func (f Float64Field) Min() AggregateFunc {
	return AggregateFunc{funcName: "MIN", field: f}
}

func (f Float64Field) Count() AggregateFunc {
	return AggregateFunc{funcName: "COUNT", field: f}
}

// ===============================================
// String Field
// ===============================================

type StringField string

func (f StringField) ColumnName() string            { return string(f) }
func (f StringField) Asc() OrderByClause            { return orderBy(string(f) + " ASC") }
func (f StringField) Desc() OrderByClause           { return orderBy(string(f) + " DESC") }
func (f StringField) AscNullsFirst() OrderByClause  { return orderBy(string(f) + " ASC NULLS FIRST") }
func (f StringField) AscNullsLast() OrderByClause   { return orderBy(string(f) + " ASC NULLS LAST") }
func (f StringField) DescNullsFirst() OrderByClause { return orderBy(string(f) + " DESC NULLS FIRST") }
func (f StringField) DescNullsLast() OrderByClause  { return orderBy(string(f) + " DESC NULLS LAST") }

func (f StringField) Eq(v string) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f StringField) Neq(v string) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

func (f StringField) In(values ...string) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): values}}
}

func (f StringField) NotIn(values ...string) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): values}}
}

// Like generates field LIKE pattern condition
func (f StringField) Like(pattern string) WhereCondition {
	return whereCondition{squirrel.Like{string(f): pattern}}
}

// NotLike generates field NOT LIKE pattern condition
func (f StringField) NotLike(pattern string) WhereCondition {
	return whereCondition{squirrel.NotLike{string(f): pattern}}
}

// ILike generates field ILIKE pattern condition (case-insensitive)
func (f StringField) ILike(pattern string) WhereCondition {
	return whereCondition{squirrel.ILike{string(f): pattern}}
}

// Aggregate functions for StringField
func (f StringField) Count() AggregateFunc {
	return AggregateFunc{funcName: "COUNT", field: f}
}

func (f StringField) Max() AggregateFunc {
	return AggregateFunc{funcName: "MAX", field: f}
}

func (f StringField) Min() AggregateFunc {
	return AggregateFunc{funcName: "MIN", field: f}
}

// ===============================================
// Bool Field
// ===============================================

type BoolField string

func (f BoolField) ColumnName() string  { return string(f) }
func (f BoolField) Asc() OrderByClause  { return orderBy(string(f) + " ASC") }
func (f BoolField) Desc() OrderByClause { return orderBy(string(f) + " DESC") }

func (f BoolField) Eq(v bool) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f BoolField) Neq(v bool) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

// IsTrue generates field = true condition
func (f BoolField) IsTrue() WhereCondition {
	return whereCondition{squirrel.Eq{string(f): true}}
}

// IsFalse generates field = false condition
func (f BoolField) IsFalse() WhereCondition {
	return whereCondition{squirrel.Eq{string(f): false}}
}

// ===============================================
// Bytes Field
// ===============================================

type BytesField string

func (f BytesField) ColumnName() string { return string(f) }

func (f BytesField) Eq(v []byte) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f BytesField) Neq(v []byte) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

// ===============================================
// Decimal Field
// ===============================================

type DecimalField string

func (f DecimalField) ColumnName() string            { return string(f) }
func (f DecimalField) Asc() OrderByClause            { return orderBy(string(f) + " ASC") }
func (f DecimalField) Desc() OrderByClause           { return orderBy(string(f) + " DESC") }
func (f DecimalField) AscNullsFirst() OrderByClause  { return orderBy(string(f) + " ASC NULLS FIRST") }
func (f DecimalField) AscNullsLast() OrderByClause   { return orderBy(string(f) + " ASC NULLS LAST") }
func (f DecimalField) DescNullsFirst() OrderByClause { return orderBy(string(f) + " DESC NULLS FIRST") }
func (f DecimalField) DescNullsLast() OrderByClause  { return orderBy(string(f) + " DESC NULLS LAST") }

func (f DecimalField) Eq(v decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f DecimalField) Neq(v decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

func (f DecimalField) Gt(v decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.Gt{string(f): v}}
}

func (f DecimalField) Gte(v decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.GtOrEq{string(f): v}}
}

func (f DecimalField) Lt(v decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.Lt{string(f): v}}
}

func (f DecimalField) Lte(v decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.LtOrEq{string(f): v}}
}

func (f DecimalField) In(values ...decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): values}}
}

func (f DecimalField) NotIn(values ...decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): values}}
}

func (f DecimalField) Between(min, max decimal.Decimal) WhereCondition {
	return whereCondition{squirrel.And{
		squirrel.GtOrEq{string(f): min},
		squirrel.LtOrEq{string(f): max},
	}}
}

// Aggregate functions for DecimalField
func (f DecimalField) Sum() AggregateFunc {
	return AggregateFunc{funcName: "SUM", field: f}
}

func (f DecimalField) Avg() AggregateFunc {
	return AggregateFunc{funcName: "AVG", field: f}
}

func (f DecimalField) Max() AggregateFunc {
	return AggregateFunc{funcName: "MAX", field: f}
}

func (f DecimalField) Min() AggregateFunc {
	return AggregateFunc{funcName: "MIN", field: f}
}

func (f DecimalField) Count() AggregateFunc {
	return AggregateFunc{funcName: "COUNT", field: f}
}

// ===============================================
// Time Field
// ===============================================

type TimeField string

func (f TimeField) ColumnName() string            { return string(f) }
func (f TimeField) Asc() OrderByClause            { return orderBy(string(f) + " ASC") }
func (f TimeField) Desc() OrderByClause           { return orderBy(string(f) + " DESC") }
func (f TimeField) AscNullsFirst() OrderByClause  { return orderBy(string(f) + " ASC NULLS FIRST") }
func (f TimeField) AscNullsLast() OrderByClause   { return orderBy(string(f) + " ASC NULLS LAST") }
func (f TimeField) DescNullsFirst() OrderByClause { return orderBy(string(f) + " DESC NULLS FIRST") }
func (f TimeField) DescNullsLast() OrderByClause  { return orderBy(string(f) + " DESC NULLS LAST") }

func (f TimeField) Eq(v time.Time) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f TimeField) Neq(v time.Time) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

func (f TimeField) Gt(v time.Time) WhereCondition {
	return whereCondition{squirrel.Gt{string(f): v}}
}

func (f TimeField) Gte(v time.Time) WhereCondition {
	return whereCondition{squirrel.GtOrEq{string(f): v}}
}

func (f TimeField) Lt(v time.Time) WhereCondition {
	return whereCondition{squirrel.Lt{string(f): v}}
}

func (f TimeField) Lte(v time.Time) WhereCondition {
	return whereCondition{squirrel.LtOrEq{string(f): v}}
}

func (f TimeField) In(values ...time.Time) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): values}}
}

func (f TimeField) NotIn(values ...time.Time) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): values}}
}

func (f TimeField) Between(start, end time.Time) WhereCondition {
	return whereCondition{squirrel.And{
		squirrel.GtOrEq{string(f): start},
		squirrel.LtOrEq{string(f): end},
	}}
}

// Aggregate functions for TimeField
func (f TimeField) Max() AggregateFunc {
	return AggregateFunc{funcName: "MAX", field: f}
}

func (f TimeField) Min() AggregateFunc {
	return AggregateFunc{funcName: "MIN", field: f}
}

func (f TimeField) Count() AggregateFunc {
	return AggregateFunc{funcName: "COUNT", field: f}
}

// ===============================================
// Array Fields
// ===============================================

type Int64ArrayField string

func (f Int64ArrayField) ColumnName() string { return string(f) }

func (f Int64ArrayField) Eq(v pq.Int64Array) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f Int64ArrayField) Neq(v pq.Int64Array) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

type StringArrayField string

func (f StringArrayField) ColumnName() string { return string(f) }

func (f StringArrayField) Eq(v pq.StringArray) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f StringArrayField) Neq(v pq.StringArray) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

type Float64ArrayField string

func (f Float64ArrayField) ColumnName() string { return string(f) }

func (f Float64ArrayField) Eq(v pq.Float64Array) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f Float64ArrayField) Neq(v pq.Float64Array) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

type BoolArrayField string

func (f BoolArrayField) ColumnName() string { return string(f) }

func (f BoolArrayField) Eq(v pq.BoolArray) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f BoolArrayField) Neq(v pq.BoolArray) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

// ===============================================
// Generic Field (fallback)
// ===============================================

type GenericField string

func (f GenericField) ColumnName() string  { return string(f) }
func (f GenericField) Asc() OrderByClause  { return orderBy(string(f) + " ASC") }
func (f GenericField) Desc() OrderByClause { return orderBy(string(f) + " DESC") }

func (f GenericField) Eq(v any) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): v}}
}

func (f GenericField) Neq(v any) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): v}}
}

func (f GenericField) In(values any) WhereCondition {
	return whereCondition{squirrel.Eq{string(f): values}}
}

func (f GenericField) NotIn(values any) WhereCondition {
	return whereCondition{squirrel.NotEq{string(f): values}}
}
