// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-19T17:23:17Z
// version: 1.0.0

package query

import (
	"context"
	"fmt"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

// orders is the query entry point for Orders
var orders = newOrdersQuery()

// Default table alias for Orders (used in JOINs)
const OrdersAlias = "orders"

// newOrdersQuery creates a new query builder for Orders
func newOrdersQuery() *ordersQuery {
	return &ordersQuery{
		fieldMap: map[string]Field{
			"id":          ordersField.ID,
			"order_id":    ordersField.OrderID,
			"client_oid":  ordersField.ClientOid,
			"exchange":    ordersField.Exchange,
			"symbol":      ordersField.Symbol,
			"side":        ordersField.Side,
			"type":        ordersField.Type,
			"price":       ordersField.Price,
			"quantity":    ordersField.Quantity,
			"amount":      ordersField.Amount,
			"status":      ordersField.Status,
			"avg_price":   ordersField.AvgPrice,
			"filled_qty":  ordersField.FilledQty,
			"cum_quote":   ordersField.CumQuote,
			"strategy_id": ordersField.StrategyID,
			"error_msg":   ordersField.ErrorMsg,
			"created_at":  ordersField.CreatedAt,
			"updated_at":  ordersField.UpdatedAt,
		},
		defaultAlias: OrdersAlias,
	}
}

// ordersQuery is the query builder for Orders
type ordersQuery struct {
	db           Executor
	fieldMap     map[string]Field
	defaultAlias string
}

// ordersField provides type-safe field access for Orders
var ordersField = struct {
	ID         Int64Field
	OrderID    StringField
	ClientOid  StringField
	Exchange   StringField
	Symbol     StringField
	Side       StringField
	Type       StringField
	Price      DecimalField
	Quantity   DecimalField
	Amount     DecimalField
	Status     StringField
	AvgPrice   DecimalField
	FilledQty  DecimalField
	CumQuote   DecimalField
	StrategyID StringField
	ErrorMsg   StringField
	CreatedAt  TimeField
	UpdatedAt  TimeField
}{
	ID:         Int64Field("id"),
	OrderID:    StringField("order_id"),
	ClientOid:  StringField("client_oid"),
	Exchange:   StringField("exchange"),
	Symbol:     StringField("symbol"),
	Side:       StringField("side"),
	Type:       StringField("type"),
	Price:      DecimalField("price"),
	Quantity:   DecimalField("quantity"),
	Amount:     DecimalField("amount"),
	Status:     StringField("status"),
	AvgPrice:   DecimalField("avg_price"),
	FilledQty:  DecimalField("filled_qty"),
	CumQuote:   DecimalField("cum_quote"),
	StrategyID: StringField("strategy_id"),
	ErrorMsg:   StringField("error_msg"),
	CreatedAt:  TimeField("created_at"),
	UpdatedAt:  TimeField("updated_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *ordersQuery) WithDB(db Executor) IOrdersDo {
	return &ordersDo{
		db:           db,
		table:        "\"public\".\"orders\"",
		alias:        q.defaultAlias, // 使用默认别名
		defaultAlias: q.defaultAlias,
		columns: []string{
			"id",
			"order_id",
			"client_oid",
			"exchange",
			"symbol",
			"side",
			"type",
			"price",
			"quantity",
			"amount",
			"status",
			"avg_price",
			"filled_qty",
			"cum_quote",
			"strategy_id",
			"error_msg",
			"created_at",
			"updated_at",
		},
		Field: &ordersField,
	}
}

// IOrdersDo defines the interface for Orders data operations
type IOrdersDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *Orders) (*Orders, error)
	BatchCreate(ctx context.Context, models []*Orders) ([]*Orders, error)
	FindByPK(ctx context.Context, iD int64) (*Orders, error)
	FindByIndex(ctx context.Context, req *OrdersIndex) ([]*OrdersIndex, error)
	UpdateByPK(ctx context.Context, model *Orders) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *Orders) (*Orders, error)
	UpsertAll(ctx context.Context, model *Orders) (*Orders, error)

	// Query builder (type-safe, only accepts fields from this table)
	As(alias string) IOrdersDo
	Where(conds ...WhereCondition) IOrdersDo
	Select(fields ...Field) IOrdersDo
	SelectAgg(aggs ...AggregateFunc) IOrdersDo
	Distinct() IOrdersDo
	GroupBy(fields ...Field) IOrdersDo
	Having(cond squirrel.Sqlizer) IOrdersDo
	Order(orderBys ...OrderByClause) IOrdersDo
	Limit(limit int) IOrdersDo
	Offset(offset int) IOrdersDo

	// Execution methods
	Find(ctx context.Context) ([]*Orders, error)
	First(ctx context.Context) (*Orders, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IOrdersDo
}

// Ensure ordersDo implements IOrdersDo
var _ IOrdersDo = (*ordersDo)(nil)

// ordersDo wraps the query builder with chainable methods
type ordersDo struct {
	db           Executor
	table        string
	alias        string // 自定义别名（通过 As() 设置）
	defaultAlias string // 默认别名（模型名）
	columns      []string
	builder      squirrel.SelectBuilder

	// Field provides type-safe field access for this model
	Field *struct {
		ID         Int64Field
		OrderID    StringField
		ClientOid  StringField
		Exchange   StringField
		Symbol     StringField
		Side       StringField
		Type       StringField
		Price      DecimalField
		Quantity   DecimalField
		Amount     DecimalField
		Status     StringField
		AvgPrice   DecimalField
		FilledQty  DecimalField
		CumQuote   DecimalField
		StrategyID StringField
		ErrorMsg   StringField
		CreatedAt  TimeField
		UpdatedAt  TimeField
	}

	// Query state
	whereSet    bool
	selectSet   bool
	distinctSet bool
	groupBySet  bool
	havingSet   bool
	orderSet    bool
	limitSet    bool
	offsetSet   bool

	// Store GROUP BY fields
	groupByFields []Field

	// Store aggregate functions for SELECT
	aggFuncs []AggregateFunc

	// Store WHERE conditions for reuse in Update/Delete
	whereConds []squirrel.Sqlizer
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *ordersDo) WithDB(db Executor) IOrdersDo {
	return &ordersDo{
		db:            db,
		table:         d.table,
		alias:         d.alias,
		defaultAlias:  d.defaultAlias,
		columns:       d.columns,
		builder:       d.builder,
		Field:         d.Field,
		whereSet:      d.whereSet,
		selectSet:     d.selectSet,
		distinctSet:   d.distinctSet,
		groupBySet:    d.groupBySet,
		havingSet:     d.havingSet,
		orderSet:      d.orderSet,
		limitSet:      d.limitSet,
		offsetSet:     d.offsetSet,
		whereConds:    d.whereConds,
		groupByFields: d.groupByFields,
		aggFuncs:      d.aggFuncs,
	}
}

// As sets a custom table alias for the query
// This is OPTIONAL - a default alias is already set automatically
// Use this only when you need a different alias (e.g., self-join)
// Example: query.user.WithDB(db).As("u1") for self-join scenarios
func (d *ordersDo) As(alias string) IOrdersDo {
	newDo := *d
	newDo.alias = alias
	newDo.Field = d.Field
	return &newDo
}

// getTableExpr returns the table expression with alias
// Always uses an alias (either custom via As() or default)
func (d *ordersDo) getTableExpr() string {
	alias := d.alias
	if alias == "" {
		alias = d.defaultAlias
	}
	return d.table + " AS " + alias
}

// Where adds WHERE conditions (chainable)
func (d *ordersDo) Where(conds ...WhereCondition) IOrdersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		sqlizer := cond.ToSqlizer()
		d.builder = d.builder.Where(sqlizer)
		d.whereConds = append(d.whereConds, sqlizer)
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *ordersDo) Select(fields ...Field) IOrdersDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Distinct adds DISTINCT to the query (chainable)
// Example: query.user.WithDB(db).Select(userField.Email).Distinct().Find(ctx)
func (d *ordersDo) Distinct() IOrdersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Distinct()
	d.distinctSet = true
	return d
}

// SelectAgg selects aggregate functions (chainable)
// Example: query.order.WithDB(db).SelectAgg(orderField.Amount.Sum().As("total"), orderField.ID.Count().As("count"))
func (d *ordersDo) SelectAgg(aggs ...AggregateFunc) IOrdersDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}

	cols := make([]string, len(aggs))
	for i, agg := range aggs {
		cols[i] = agg.ToSQL()
	}
	d.builder = d.builder.Columns(cols...)
	d.aggFuncs = append(d.aggFuncs, aggs...)
	return d
}

// GroupBy adds GROUP BY clause (chainable)
// Example: query.order.WithDB(db).Select(orderField.UserID).SelectAgg(orderField.Amount.Sum()).GroupBy(orderField.UserID)
func (d *ordersDo) GroupBy(fields ...Field) IOrdersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.GroupBy(cols...)
	d.groupBySet = true
	d.groupByFields = append(d.groupByFields, fields...)
	return d
}

// Having adds HAVING clause (chainable, used with GROUP BY)
// Example: query.order.WithDB(db).GroupBy(orderField.UserID).Having(squirrel.Gt{"SUM(amount)": 1000})
func (d *ordersDo) Having(cond squirrel.Sqlizer) IOrdersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Having(cond)
	d.havingSet = true
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., ordersField.Age.Desc())
func (d *ordersDo) Order(orderBys ...OrderByClause) IOrdersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *ordersDo) Limit(limit int) IOrdersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *ordersDo) Offset(offset int) IOrdersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *ordersDo) Find(ctx context.Context) ([]*Orders, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}
	var results []*Orders
	err = d.db.QueryRowsCtx(ctx, &results, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	return results, nil
}

// First executes the query and returns the first matching record
func (d *ordersDo) First(ctx context.Context) (*Orders, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result Orders
	err = d.db.QueryRowCtx(ctx, &result, query, args...)
	if err == sqlx.ErrNotFound {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *ordersDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		countBuilder = countBuilder.Where(cond)
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowCtx(ctx, &count, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *ordersDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *ordersDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
