// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/Masterminds/squirrel"
)

// riskRecords is the query entry point for RiskRecords
var riskRecords = newRiskRecordsQuery()

// newRiskRecordsQuery creates a new query builder for RiskRecords
func newRiskRecordsQuery() *riskRecordsQuery {
	return &riskRecordsQuery{
		fieldMap: map[string]Field{
			"id":           riskRecordsField.ID,
			"event_type":   riskRecordsField.EventType,
			"level":        riskRecordsField.Level,
			"symbol":       riskRecordsField.Symbol,
			"strategy_id":  riskRecordsField.StrategyID,
			"details":      riskRecordsField.Details,
			"triggered_at": riskRecordsField.TriggeredAt,
		},
	}
}

// riskRecordsQuery is the query builder for RiskRecords
type riskRecordsQuery struct {
	db       Executor
	fieldMap map[string]Field
}

// riskRecordsField provides type-safe field access for RiskRecords
var riskRecordsField = struct {
	ID          Int64Field
	EventType   StringField
	Level       StringField
	Symbol      StringField
	StrategyID  StringField
	Details     StringField
	TriggeredAt TimeField
}{
	ID:          Int64Field("id"),
	EventType:   StringField("event_type"),
	Level:       StringField("level"),
	Symbol:      StringField("symbol"),
	StrategyID:  StringField("strategy_id"),
	Details:     StringField("details"),
	TriggeredAt: TimeField("triggered_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *riskRecordsQuery) WithDB(db Executor) IRiskRecordsDo {
	return &riskRecordsDo{
		db:    db,
		table: "\"public\".\"risk_records\"",
		columns: []string{
			"id",
			"event_type",
			"level",
			"symbol",
			"strategy_id",
			"details",
			"triggered_at",
		},
	}
}

// As creates a table alias for the query
func (q *riskRecordsQuery) As(alias string) *riskRecordsQuery {
	return q
}

// IRiskRecordsDo defines the interface for RiskRecords data operations
type IRiskRecordsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *RiskRecords) (*RiskRecords, error)
	BatchCreate(ctx context.Context, models []*RiskRecords) ([]*RiskRecords, error)
	FindByPK(ctx context.Context, iD int64) (*RiskRecords, error)
	FindByIndex(ctx context.Context, req *RiskRecordsIndex) ([]*RiskRecordsIndex, error)
	UpdateByPK(ctx context.Context, model *RiskRecords) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *RiskRecords) (*RiskRecords, error)
	UpsertAll(ctx context.Context, model *RiskRecords) (*RiskRecords, error)

	// Query builder (type-safe, only accepts fields from this table)
	Where(conds ...WhereCondition) IRiskRecordsDo
	Select(fields ...Field) IRiskRecordsDo
	Order(orderBys ...OrderByClause) IRiskRecordsDo
	Limit(limit int) IRiskRecordsDo
	Offset(offset int) IRiskRecordsDo

	// Execution methods
	Find(ctx context.Context) ([]*RiskRecords, error)
	First(ctx context.Context) (*RiskRecords, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IRiskRecordsDo
}

// Ensure riskRecordsDo implements IRiskRecordsDo
var _ IRiskRecordsDo = (*riskRecordsDo)(nil)

// riskRecordsDo wraps the query builder with chainable methods
type riskRecordsDo struct {
	db      Executor
	table   string
	columns []string
	builder squirrel.SelectBuilder

	// Query state
	whereSet  bool
	selectSet bool
	orderSet  bool
	limitSet  bool
	offsetSet bool
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *riskRecordsDo) WithDB(db Executor) IRiskRecordsDo {
	return &riskRecordsDo{
		db:      db,
		table:   d.table,
		columns: d.columns,
	}
}

// Where adds WHERE conditions (chainable)
func (d *riskRecordsDo) Where(conds ...WhereCondition) IRiskRecordsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		d.builder = d.builder.Where(cond.ToSqlizer())
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *riskRecordsDo) Select(fields ...Field) IRiskRecordsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., riskRecordsField.Age.Desc())
func (d *riskRecordsDo) Order(orderBys ...OrderByClause) IRiskRecordsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *riskRecordsDo) Limit(limit int) IRiskRecordsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *riskRecordsDo) Offset(offset int) IRiskRecordsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *riskRecordsDo) Find(ctx context.Context) ([]*RiskRecords, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	defer rows.Close()

	var results []*RiskRecords
	for rows.Next() {
		var result RiskRecords
		err := rows.Scan(
			&result.ID,
			&result.EventType,
			&result.Level,
			&result.Symbol,
			&result.StrategyID,
			&result.Details,
			&result.TriggeredAt,
		)
		if err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// First executes the query and returns the first matching record
func (d *riskRecordsDo) First(ctx context.Context) (*RiskRecords, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result RiskRecords
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.EventType,
		&result.Level,
		&result.Symbol,
		&result.StrategyID,
		&result.Details,
		&result.TriggeredAt,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *riskRecordsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.table).PlaceholderFormat(squirrel.Dollar)

	if d.whereSet {
		// Extract WHERE clauses from existing builder if any
		query, args, err := d.builder.ToSql()
		if err != nil {
			return 0, fmt.Errorf("build count query: %w", err)
		}
		// Parse WHERE clause from the query
		_ = query // TODO: extract WHERE clause properly
		_ = args
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowContext(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *riskRecordsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *riskRecordsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
