// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/Masterminds/squirrel"
)

// strategyConfigs is the query entry point for StrategyConfigs
var strategyConfigs = newStrategyConfigsQuery()

// newStrategyConfigsQuery creates a new query builder for StrategyConfigs
func newStrategyConfigsQuery() *strategyConfigsQuery {
	return &strategyConfigsQuery{
		fieldMap: map[string]Field{
			"key_name":    strategyConfigsField.KeyName,
			"value_str":   strategyConfigsField.ValueStr,
			"value_num":   strategyConfigsField.ValueNum,
			"description": strategyConfigsField.Description,
			"updated_at":  strategyConfigsField.UpdatedAt,
		},
	}
}

// strategyConfigsQuery is the query builder for StrategyConfigs
type strategyConfigsQuery struct {
	db       Executor
	fieldMap map[string]Field
}

// strategyConfigsField provides type-safe field access for StrategyConfigs
var strategyConfigsField = struct {
	KeyName     StringField
	ValueStr    StringField
	ValueNum    DecimalField
	Description StringField
	UpdatedAt   TimeField
}{
	KeyName:     StringField("key_name"),
	ValueStr:    StringField("value_str"),
	ValueNum:    DecimalField("value_num"),
	Description: StringField("description"),
	UpdatedAt:   TimeField("updated_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *strategyConfigsQuery) WithDB(db Executor) IStrategyConfigsDo {
	return &strategyConfigsDo{
		db:    db,
		table: "\"public\".\"strategy_configs\"",
		columns: []string{
			"key_name",
			"value_str",
			"value_num",
			"description",
			"updated_at",
		},
	}
}

// As creates a table alias for the query
func (q *strategyConfigsQuery) As(alias string) *strategyConfigsQuery {
	return q
}

// IStrategyConfigsDo defines the interface for StrategyConfigs data operations
type IStrategyConfigsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *StrategyConfigs) (*StrategyConfigs, error)
	BatchCreate(ctx context.Context, models []*StrategyConfigs) ([]*StrategyConfigs, error)
	FindByPK(ctx context.Context, keyName string) (*StrategyConfigs, error)
	FindByIndex(ctx context.Context, req *StrategyConfigsIndex) ([]*StrategyConfigsIndex, error)
	UpdateByPK(ctx context.Context, model *StrategyConfigs) error
	DeleteByPK(ctx context.Context, keyName string) error
	Upsert(ctx context.Context, model *StrategyConfigs) (*StrategyConfigs, error)
	UpsertAll(ctx context.Context, model *StrategyConfigs) (*StrategyConfigs, error)

	// Query builder (type-safe, only accepts fields from this table)
	Where(conds ...WhereCondition) IStrategyConfigsDo
	Select(fields ...Field) IStrategyConfigsDo
	Order(orderBys ...OrderByClause) IStrategyConfigsDo
	Limit(limit int) IStrategyConfigsDo
	Offset(offset int) IStrategyConfigsDo

	// Execution methods
	Find(ctx context.Context) ([]*StrategyConfigs, error)
	First(ctx context.Context) (*StrategyConfigs, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IStrategyConfigsDo
}

// Ensure strategyConfigsDo implements IStrategyConfigsDo
var _ IStrategyConfigsDo = (*strategyConfigsDo)(nil)

// strategyConfigsDo wraps the query builder with chainable methods
type strategyConfigsDo struct {
	db      Executor
	table   string
	columns []string
	builder squirrel.SelectBuilder

	// Query state
	whereSet  bool
	selectSet bool
	orderSet  bool
	limitSet  bool
	offsetSet bool
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *strategyConfigsDo) WithDB(db Executor) IStrategyConfigsDo {
	return &strategyConfigsDo{
		db:      db,
		table:   d.table,
		columns: d.columns,
	}
}

// Where adds WHERE conditions (chainable)
func (d *strategyConfigsDo) Where(conds ...WhereCondition) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		d.builder = d.builder.Where(cond.ToSqlizer())
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *strategyConfigsDo) Select(fields ...Field) IStrategyConfigsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., strategyConfigsField.Age.Desc())
func (d *strategyConfigsDo) Order(orderBys ...OrderByClause) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *strategyConfigsDo) Limit(limit int) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *strategyConfigsDo) Offset(offset int) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *strategyConfigsDo) Find(ctx context.Context) ([]*StrategyConfigs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	defer rows.Close()

	var results []*StrategyConfigs
	for rows.Next() {
		var result StrategyConfigs
		err := rows.Scan(
			&result.KeyName,
			&result.ValueStr,
			&result.ValueNum,
			&result.Description,
			&result.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// First executes the query and returns the first matching record
func (d *strategyConfigsDo) First(ctx context.Context) (*StrategyConfigs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result StrategyConfigs
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.KeyName,
		&result.ValueStr,
		&result.ValueNum,
		&result.Description,
		&result.UpdatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *strategyConfigsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.table).PlaceholderFormat(squirrel.Dollar)

	if d.whereSet {
		// Extract WHERE clauses from existing builder if any
		query, args, err := d.builder.ToSql()
		if err != nil {
			return 0, fmt.Errorf("build count query: %w", err)
		}
		// Parse WHERE clause from the query
		_ = query // TODO: extract WHERE clause properly
		_ = args
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowContext(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *strategyConfigsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *strategyConfigsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
