// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-19T17:23:17Z
// version: 1.0.0

package query

import (
	"context"
	"fmt"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

// strategyConfigs is the query entry point for StrategyConfigs
var strategyConfigs = newStrategyConfigsQuery()

// Default table alias for StrategyConfigs (used in JOINs)
const StrategyConfigsAlias = "strategyConfigs"

// newStrategyConfigsQuery creates a new query builder for StrategyConfigs
func newStrategyConfigsQuery() *strategyConfigsQuery {
	return &strategyConfigsQuery{
		fieldMap: map[string]Field{
			"key_name":    strategyConfigsField.KeyName,
			"value_str":   strategyConfigsField.ValueStr,
			"value_num":   strategyConfigsField.ValueNum,
			"description": strategyConfigsField.Description,
			"updated_at":  strategyConfigsField.UpdatedAt,
		},
		defaultAlias: StrategyConfigsAlias,
	}
}

// strategyConfigsQuery is the query builder for StrategyConfigs
type strategyConfigsQuery struct {
	db           Executor
	fieldMap     map[string]Field
	defaultAlias string
}

// strategyConfigsField provides type-safe field access for StrategyConfigs
var strategyConfigsField = struct {
	KeyName     StringField
	ValueStr    StringField
	ValueNum    DecimalField
	Description StringField
	UpdatedAt   TimeField
}{
	KeyName:     StringField("key_name"),
	ValueStr:    StringField("value_str"),
	ValueNum:    DecimalField("value_num"),
	Description: StringField("description"),
	UpdatedAt:   TimeField("updated_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *strategyConfigsQuery) WithDB(db Executor) IStrategyConfigsDo {
	return &strategyConfigsDo{
		db:           db,
		table:        "\"public\".\"strategy_configs\"",
		alias:        q.defaultAlias, // 使用默认别名
		defaultAlias: q.defaultAlias,
		columns: []string{
			"key_name",
			"value_str",
			"value_num",
			"description",
			"updated_at",
		},
		Field: &strategyConfigsField,
	}
}

// IStrategyConfigsDo defines the interface for StrategyConfigs data operations
type IStrategyConfigsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *StrategyConfigs) (*StrategyConfigs, error)
	BatchCreate(ctx context.Context, models []*StrategyConfigs) ([]*StrategyConfigs, error)
	FindByPK(ctx context.Context, keyName string) (*StrategyConfigs, error)
	FindByIndex(ctx context.Context, req *StrategyConfigsIndex) ([]*StrategyConfigsIndex, error)
	UpdateByPK(ctx context.Context, model *StrategyConfigs) error
	DeleteByPK(ctx context.Context, keyName string) error
	Upsert(ctx context.Context, model *StrategyConfigs) (*StrategyConfigs, error)
	UpsertAll(ctx context.Context, model *StrategyConfigs) (*StrategyConfigs, error)

	// Query builder (type-safe, only accepts fields from this table)
	As(alias string) IStrategyConfigsDo
	Where(conds ...WhereCondition) IStrategyConfigsDo
	Select(fields ...Field) IStrategyConfigsDo
	SelectAgg(aggs ...AggregateFunc) IStrategyConfigsDo
	Distinct() IStrategyConfigsDo
	GroupBy(fields ...Field) IStrategyConfigsDo
	Having(cond squirrel.Sqlizer) IStrategyConfigsDo
	Order(orderBys ...OrderByClause) IStrategyConfigsDo
	Limit(limit int) IStrategyConfigsDo
	Offset(offset int) IStrategyConfigsDo

	// Execution methods
	Find(ctx context.Context) ([]*StrategyConfigs, error)
	First(ctx context.Context) (*StrategyConfigs, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IStrategyConfigsDo
}

// Ensure strategyConfigsDo implements IStrategyConfigsDo
var _ IStrategyConfigsDo = (*strategyConfigsDo)(nil)

// strategyConfigsDo wraps the query builder with chainable methods
type strategyConfigsDo struct {
	db           Executor
	table        string
	alias        string // 自定义别名（通过 As() 设置）
	defaultAlias string // 默认别名（模型名）
	columns      []string
	builder      squirrel.SelectBuilder

	// Field provides type-safe field access for this model
	Field *struct {
		KeyName     StringField
		ValueStr    StringField
		ValueNum    DecimalField
		Description StringField
		UpdatedAt   TimeField
	}

	// Query state
	whereSet    bool
	selectSet   bool
	distinctSet bool
	groupBySet  bool
	havingSet   bool
	orderSet    bool
	limitSet    bool
	offsetSet   bool

	// Store GROUP BY fields
	groupByFields []Field

	// Store aggregate functions for SELECT
	aggFuncs []AggregateFunc

	// Store WHERE conditions for reuse in Update/Delete
	whereConds []squirrel.Sqlizer
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *strategyConfigsDo) WithDB(db Executor) IStrategyConfigsDo {
	return &strategyConfigsDo{
		db:            db,
		table:         d.table,
		alias:         d.alias,
		defaultAlias:  d.defaultAlias,
		columns:       d.columns,
		builder:       d.builder,
		Field:         d.Field,
		whereSet:      d.whereSet,
		selectSet:     d.selectSet,
		distinctSet:   d.distinctSet,
		groupBySet:    d.groupBySet,
		havingSet:     d.havingSet,
		orderSet:      d.orderSet,
		limitSet:      d.limitSet,
		offsetSet:     d.offsetSet,
		whereConds:    d.whereConds,
		groupByFields: d.groupByFields,
		aggFuncs:      d.aggFuncs,
	}
}

// As sets a custom table alias for the query
// This is OPTIONAL - a default alias is already set automatically
// Use this only when you need a different alias (e.g., self-join)
// Example: query.user.WithDB(db).As("u1") for self-join scenarios
func (d *strategyConfigsDo) As(alias string) IStrategyConfigsDo {
	newDo := *d
	newDo.alias = alias
	newDo.Field = d.Field
	return &newDo
}

// getTableExpr returns the table expression with alias
// Always uses an alias (either custom via As() or default)
func (d *strategyConfigsDo) getTableExpr() string {
	alias := d.alias
	if alias == "" {
		alias = d.defaultAlias
	}
	return d.table + " AS " + alias
}

// Where adds WHERE conditions (chainable)
func (d *strategyConfigsDo) Where(conds ...WhereCondition) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		sqlizer := cond.ToSqlizer()
		d.builder = d.builder.Where(sqlizer)
		d.whereConds = append(d.whereConds, sqlizer)
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *strategyConfigsDo) Select(fields ...Field) IStrategyConfigsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Distinct adds DISTINCT to the query (chainable)
// Example: query.user.WithDB(db).Select(userField.Email).Distinct().Find(ctx)
func (d *strategyConfigsDo) Distinct() IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Distinct()
	d.distinctSet = true
	return d
}

// SelectAgg selects aggregate functions (chainable)
// Example: query.order.WithDB(db).SelectAgg(orderField.Amount.Sum().As("total"), orderField.ID.Count().As("count"))
func (d *strategyConfigsDo) SelectAgg(aggs ...AggregateFunc) IStrategyConfigsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}

	cols := make([]string, len(aggs))
	for i, agg := range aggs {
		cols[i] = agg.ToSQL()
	}
	d.builder = d.builder.Columns(cols...)
	d.aggFuncs = append(d.aggFuncs, aggs...)
	return d
}

// GroupBy adds GROUP BY clause (chainable)
// Example: query.order.WithDB(db).Select(orderField.UserID).SelectAgg(orderField.Amount.Sum()).GroupBy(orderField.UserID)
func (d *strategyConfigsDo) GroupBy(fields ...Field) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.GroupBy(cols...)
	d.groupBySet = true
	d.groupByFields = append(d.groupByFields, fields...)
	return d
}

// Having adds HAVING clause (chainable, used with GROUP BY)
// Example: query.order.WithDB(db).GroupBy(orderField.UserID).Having(squirrel.Gt{"SUM(amount)": 1000})
func (d *strategyConfigsDo) Having(cond squirrel.Sqlizer) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Having(cond)
	d.havingSet = true
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., strategyConfigsField.Age.Desc())
func (d *strategyConfigsDo) Order(orderBys ...OrderByClause) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *strategyConfigsDo) Limit(limit int) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *strategyConfigsDo) Offset(offset int) IStrategyConfigsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *strategyConfigsDo) Find(ctx context.Context) ([]*StrategyConfigs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}
	var results []*StrategyConfigs
	err = d.db.QueryRowsCtx(ctx, &results, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	return results, nil
}

// First executes the query and returns the first matching record
func (d *strategyConfigsDo) First(ctx context.Context) (*StrategyConfigs, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result StrategyConfigs
	err = d.db.QueryRowCtx(ctx, &result, query, args...)
	if err == sqlx.ErrNotFound {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *strategyConfigsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		countBuilder = countBuilder.Where(cond)
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowCtx(ctx, &count, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *strategyConfigsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *strategyConfigsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
