// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-19T18:09:36Z
// version: 1.0.0

package query

import (
	"context"
	"fmt"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

// users is the query entry point for Users
var users = newUsersQuery()

// Default table alias for Users (used in JOINs)
const UsersAlias = "users"

// newUsersQuery creates a new query builder for Users
func newUsersQuery() *usersQuery {
	return &usersQuery{
		fieldMap: map[string]Field{
			"id":                usersField.ID,
			"uuid":              usersField.Uuid,
			"username":          usersField.Username,
			"display_name":      usersField.DisplayName,
			"avatar":            usersField.Avatar,
			"password_hash":     usersField.PasswordHash,
			"is_active":         usersField.IsActive,
			"created_at":        usersField.CreatedAt,
			"updated_at":        usersField.UpdatedAt,
			"revoked_at":        usersField.RevokedAt,
			"github_id":         usersField.GithubID,
			"google_id":         usersField.GoogleID,
			"totp_secret":       usersField.TotpSecret,
			"totp_enabled":      usersField.TotpEnabled,
			"totp_backup_codes": usersField.TotpBackupCodes,
		},
		defaultAlias: UsersAlias,
	}
}

// usersQuery is the query builder for Users
type usersQuery struct {
	db           Executor
	fieldMap     map[string]Field
	defaultAlias string
}

// usersField provides type-safe field access for Users
var usersField = struct {
	ID              Int64Field
	Uuid            StringField
	Username        StringField
	DisplayName     StringField
	Avatar          StringField
	PasswordHash    StringField
	IsActive        BoolField
	CreatedAt       TimeField
	UpdatedAt       TimeField
	RevokedAt       TimeField
	GithubID        StringField
	GoogleID        StringField
	TotpSecret      StringField
	TotpEnabled     BoolField
	TotpBackupCodes StringField
}{
	ID:              Int64Field("id"),
	Uuid:            StringField("uuid"),
	Username:        StringField("username"),
	DisplayName:     StringField("display_name"),
	Avatar:          StringField("avatar"),
	PasswordHash:    StringField("password_hash"),
	IsActive:        BoolField("is_active"),
	CreatedAt:       TimeField("created_at"),
	UpdatedAt:       TimeField("updated_at"),
	RevokedAt:       TimeField("revoked_at"),
	GithubID:        StringField("github_id"),
	GoogleID:        StringField("google_id"),
	TotpSecret:      StringField("totp_secret"),
	TotpEnabled:     BoolField("totp_enabled"),
	TotpBackupCodes: StringField("totp_backup_codes"),
}

// WithDB returns a new query instance with the given database executor
func (q *usersQuery) WithDB(db Executor) IUsersDo {
	return &usersDo{
		db:           db,
		table:        "\"public\".\"users\"",
		alias:        q.defaultAlias, // 使用默认别名
		defaultAlias: q.defaultAlias,
		columns: []string{
			"id",
			"uuid",
			"username",
			"display_name",
			"avatar",
			"password_hash",
			"is_active",
			"created_at",
			"updated_at",
			"revoked_at",
			"github_id",
			"google_id",
			"totp_secret",
			"totp_enabled",
			"totp_backup_codes",
		},
		Field: &usersField,
	}
}

// IUsersDo defines the interface for Users data operations
type IUsersDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *Users) (*Users, error)
	BatchCreate(ctx context.Context, models []*Users) ([]*Users, error)
	FindByPK(ctx context.Context, iD int64) (*Users, error)
	FindByIndex(ctx context.Context, req *UsersIndex) ([]*UsersIndex, error)
	UpdateByPK(ctx context.Context, model *Users) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *Users) (*Users, error)
	UpsertAll(ctx context.Context, model *Users) (*Users, error)

	// Query builder (type-safe, only accepts fields from this table)
	As(alias string) IUsersDo
	Where(conds ...WhereCondition) IUsersDo
	Select(fields ...Field) IUsersDo
	SelectAgg(aggs ...AggregateFunc) IUsersDo
	Distinct() IUsersDo
	GroupBy(fields ...Field) IUsersDo
	Having(cond squirrel.Sqlizer) IUsersDo
	Order(orderBys ...OrderByClause) IUsersDo
	Limit(limit int) IUsersDo
	Offset(offset int) IUsersDo

	// Execution methods
	Find(ctx context.Context) ([]*Users, error)
	First(ctx context.Context) (*Users, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IUsersDo
}

// Ensure usersDo implements IUsersDo
var _ IUsersDo = (*usersDo)(nil)

// usersDo wraps the query builder with chainable methods
type usersDo struct {
	db           Executor
	table        string
	alias        string // 自定义别名（通过 As() 设置）
	defaultAlias string // 默认别名（模型名）
	columns      []string
	builder      squirrel.SelectBuilder

	// Field provides type-safe field access for this model
	Field *struct {
		ID              Int64Field
		Uuid            StringField
		Username        StringField
		DisplayName     StringField
		Avatar          StringField
		PasswordHash    StringField
		IsActive        BoolField
		CreatedAt       TimeField
		UpdatedAt       TimeField
		RevokedAt       TimeField
		GithubID        StringField
		GoogleID        StringField
		TotpSecret      StringField
		TotpEnabled     BoolField
		TotpBackupCodes StringField
	}

	// Query state
	whereSet    bool
	selectSet   bool
	distinctSet bool
	groupBySet  bool
	havingSet   bool
	orderSet    bool
	limitSet    bool
	offsetSet   bool

	// Store GROUP BY fields
	groupByFields []Field

	// Store aggregate functions for SELECT
	aggFuncs []AggregateFunc

	// Store WHERE conditions for reuse in Update/Delete
	whereConds []squirrel.Sqlizer
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *usersDo) WithDB(db Executor) IUsersDo {
	return &usersDo{
		db:            db,
		table:         d.table,
		alias:         d.alias,
		defaultAlias:  d.defaultAlias,
		columns:       d.columns,
		builder:       d.builder,
		Field:         d.Field,
		whereSet:      d.whereSet,
		selectSet:     d.selectSet,
		distinctSet:   d.distinctSet,
		groupBySet:    d.groupBySet,
		havingSet:     d.havingSet,
		orderSet:      d.orderSet,
		limitSet:      d.limitSet,
		offsetSet:     d.offsetSet,
		whereConds:    d.whereConds,
		groupByFields: d.groupByFields,
		aggFuncs:      d.aggFuncs,
	}
}

// As sets a custom table alias for the query
// This is OPTIONAL - a default alias is already set automatically
// Use this only when you need a different alias (e.g., self-join)
// Example: query.user.WithDB(db).As("u1") for self-join scenarios
func (d *usersDo) As(alias string) IUsersDo {
	newDo := *d
	newDo.alias = alias
	newDo.Field = d.Field
	return &newDo
}

// getTableExpr returns the table expression with alias
// Always uses an alias (either custom via As() or default)
func (d *usersDo) getTableExpr() string {
	alias := d.alias
	if alias == "" {
		alias = d.defaultAlias
	}
	return d.table + " AS " + alias
}

// Where adds WHERE conditions (chainable)
func (d *usersDo) Where(conds ...WhereCondition) IUsersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		sqlizer := cond.ToSqlizer()
		d.builder = d.builder.Where(sqlizer)
		d.whereConds = append(d.whereConds, sqlizer)
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *usersDo) Select(fields ...Field) IUsersDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Distinct adds DISTINCT to the query (chainable)
// Example: query.user.WithDB(db).Select(userField.Email).Distinct().Find(ctx)
func (d *usersDo) Distinct() IUsersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Distinct()
	d.distinctSet = true
	return d
}

// SelectAgg selects aggregate functions (chainable)
// Example: query.order.WithDB(db).SelectAgg(orderField.Amount.Sum().As("total"), orderField.ID.Count().As("count"))
func (d *usersDo) SelectAgg(aggs ...AggregateFunc) IUsersDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}

	cols := make([]string, len(aggs))
	for i, agg := range aggs {
		cols[i] = agg.ToSQL()
	}
	d.builder = d.builder.Columns(cols...)
	d.aggFuncs = append(d.aggFuncs, aggs...)
	return d
}

// GroupBy adds GROUP BY clause (chainable)
// Example: query.order.WithDB(db).Select(orderField.UserID).SelectAgg(orderField.Amount.Sum()).GroupBy(orderField.UserID)
func (d *usersDo) GroupBy(fields ...Field) IUsersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.GroupBy(cols...)
	d.groupBySet = true
	d.groupByFields = append(d.groupByFields, fields...)
	return d
}

// Having adds HAVING clause (chainable, used with GROUP BY)
// Example: query.order.WithDB(db).GroupBy(orderField.UserID).Having(squirrel.Gt{"SUM(amount)": 1000})
func (d *usersDo) Having(cond squirrel.Sqlizer) IUsersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Having(cond)
	d.havingSet = true
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., usersField.Age.Desc())
func (d *usersDo) Order(orderBys ...OrderByClause) IUsersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *usersDo) Limit(limit int) IUsersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *usersDo) Offset(offset int) IUsersDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *usersDo) Find(ctx context.Context) ([]*Users, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}
	var results []*Users
	err = d.db.QueryRowsCtx(ctx, &results, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	return results, nil
}

// First executes the query and returns the first matching record
func (d *usersDo) First(ctx context.Context) (*Users, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}

	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result Users
	err = d.db.QueryRowCtx(ctx, &result, query, args...)
	if err == sqlx.ErrNotFound {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *usersDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.getTableExpr()).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		countBuilder = countBuilder.Where(cond)
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowCtx(ctx, &count, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *usersDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *usersDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// Apply stored WHERE conditions
	for _, cond := range d.whereConds {
		builder = builder.Where(cond)
	}

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}
	result, err := d.db.ExecCtx(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
