// Code generated by gpmg. DO NOT EDIT.
// generated_at_utc: 2026-01-18T14:25:30Z
// version: 1.0.0

package query

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/Masterminds/squirrel"
)

// webauthnCredentials is the query entry point for WebauthnCredentials
var webauthnCredentials = newWebauthnCredentialsQuery()

// newWebauthnCredentialsQuery creates a new query builder for WebauthnCredentials
func newWebauthnCredentialsQuery() *webauthnCredentialsQuery {
	return &webauthnCredentialsQuery{
		fieldMap: map[string]Field{
			"id":               webauthnCredentialsField.ID,
			"user_id":          webauthnCredentialsField.UserID,
			"webauthn_id":      webauthnCredentialsField.WebauthnID,
			"public_key":       webauthnCredentialsField.PublicKey,
			"attestation_type": webauthnCredentialsField.AttestationType,
			"transport":        webauthnCredentialsField.Transport,
			"aaguid":           webauthnCredentialsField.Aaguid,
			"sign_count":       webauthnCredentialsField.SignCount,
			"clone_warning":    webauthnCredentialsField.CloneWarning,
			"device_name":      webauthnCredentialsField.DeviceName,
			"created_at":       webauthnCredentialsField.CreatedAt,
			"last_used_at":     webauthnCredentialsField.LastUsedAt,
		},
	}
}

// webauthnCredentialsQuery is the query builder for WebauthnCredentials
type webauthnCredentialsQuery struct {
	db       Executor
	fieldMap map[string]Field
}

// webauthnCredentialsField provides type-safe field access for WebauthnCredentials
var webauthnCredentialsField = struct {
	ID              Int64Field
	UserID          Int64Field
	WebauthnID      BytesField
	PublicKey       BytesField
	AttestationType StringField
	Transport       StringField
	Aaguid          StringField
	SignCount       Int64Field
	CloneWarning    BoolField
	DeviceName      StringField
	CreatedAt       TimeField
	LastUsedAt      TimeField
}{
	ID:              Int64Field("id"),
	UserID:          Int64Field("user_id"),
	WebauthnID:      BytesField("webauthn_id"),
	PublicKey:       BytesField("public_key"),
	AttestationType: StringField("attestation_type"),
	Transport:       StringField("transport"),
	Aaguid:          StringField("aaguid"),
	SignCount:       Int64Field("sign_count"),
	CloneWarning:    BoolField("clone_warning"),
	DeviceName:      StringField("device_name"),
	CreatedAt:       TimeField("created_at"),
	LastUsedAt:      TimeField("last_used_at"),
}

// WithDB returns a new query instance with the given database executor
func (q *webauthnCredentialsQuery) WithDB(db Executor) IWebauthnCredentialsDo {
	return &webauthnCredentialsDo{
		db:    db,
		table: "\"public\".\"webauthn_credentials\"",
		columns: []string{
			"id",
			"user_id",
			"webauthn_id",
			"public_key",
			"attestation_type",
			"transport",
			"aaguid",
			"sign_count",
			"clone_warning",
			"device_name",
			"created_at",
			"last_used_at",
		},
	}
}

// As creates a table alias for the query
func (q *webauthnCredentialsQuery) As(alias string) *webauthnCredentialsQuery {
	return q
}

// IWebauthnCredentialsDo defines the interface for WebauthnCredentials data operations
type IWebauthnCredentialsDo interface {
	// Basic CRUD operations
	Create(ctx context.Context, model *WebauthnCredentials) (*WebauthnCredentials, error)
	BatchCreate(ctx context.Context, models []*WebauthnCredentials) ([]*WebauthnCredentials, error)
	FindByPK(ctx context.Context, iD int64) (*WebauthnCredentials, error)
	FindByIndex(ctx context.Context, req *WebauthnCredentialsIndex) ([]*WebauthnCredentialsIndex, error)
	UpdateByPK(ctx context.Context, model *WebauthnCredentials) error
	DeleteByPK(ctx context.Context, iD int64) error
	Upsert(ctx context.Context, model *WebauthnCredentials) (*WebauthnCredentials, error)
	UpsertAll(ctx context.Context, model *WebauthnCredentials) (*WebauthnCredentials, error)

	// Query builder (type-safe, only accepts fields from this table)
	Where(conds ...WhereCondition) IWebauthnCredentialsDo
	Select(fields ...Field) IWebauthnCredentialsDo
	Order(orderBys ...OrderByClause) IWebauthnCredentialsDo
	Limit(limit int) IWebauthnCredentialsDo
	Offset(offset int) IWebauthnCredentialsDo

	// Execution methods
	Find(ctx context.Context) ([]*WebauthnCredentials, error)
	First(ctx context.Context) (*WebauthnCredentials, error)
	Count(ctx context.Context) (int64, error)
	Update(ctx context.Context, updates map[string]interface{}) (int64, error)
	Delete(ctx context.Context) (int64, error)

	// Transaction support
	WithDB(db Executor) IWebauthnCredentialsDo
}

// Ensure webauthnCredentialsDo implements IWebauthnCredentialsDo
var _ IWebauthnCredentialsDo = (*webauthnCredentialsDo)(nil)

// webauthnCredentialsDo wraps the query builder with chainable methods
type webauthnCredentialsDo struct {
	db      Executor
	table   string
	columns []string
	builder squirrel.SelectBuilder

	// Query state
	whereSet  bool
	selectSet bool
	orderSet  bool
	limitSet  bool
	offsetSet bool
}

// WithDB returns a new DO instance with the given database executor (for transactions)
func (d *webauthnCredentialsDo) WithDB(db Executor) IWebauthnCredentialsDo {
	return &webauthnCredentialsDo{
		db:      db,
		table:   d.table,
		columns: d.columns,
	}
}

// Where adds WHERE conditions (chainable)
func (d *webauthnCredentialsDo) Where(conds ...WhereCondition) IWebauthnCredentialsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	for _, cond := range conds {
		d.builder = d.builder.Where(cond.ToSqlizer())
	}
	return d
}

// Select specifies which fields to select (chainable)
func (d *webauthnCredentialsDo) Select(fields ...Field) IWebauthnCredentialsDo {
	if !d.selectSet {
		if !d.whereSet {
			d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
			d.whereSet = true
		}
		d.selectSet = true
	}
	cols := make([]string, len(fields))
	for i, f := range fields {
		cols[i] = f.ColumnName()
	}
	d.builder = d.builder.Columns(cols...)
	return d
}

// Order adds ORDER BY clause (chainable, type-safe)
// Only accepts OrderByClause from this table's fields (e.g., webauthnCredentialsField.Age.Desc())
func (d *webauthnCredentialsDo) Order(orderBys ...OrderByClause) IWebauthnCredentialsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	orderStrs := make([]string, len(orderBys))
	for i, ob := range orderBys {
		orderStrs[i] = ob.ToSQL()
	}
	d.builder = d.builder.OrderBy(orderStrs...)
	d.orderSet = true
	return d
}

// Limit sets the LIMIT clause (chainable)
func (d *webauthnCredentialsDo) Limit(limit int) IWebauthnCredentialsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Limit(uint64(limit))
	d.limitSet = true
	return d
}

// Offset sets the OFFSET clause (chainable)
func (d *webauthnCredentialsDo) Offset(offset int) IWebauthnCredentialsDo {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	d.builder = d.builder.Offset(uint64(offset))
	d.offsetSet = true
	return d
}

// Find executes the query and returns all matching records
func (d *webauthnCredentialsDo) Find(ctx context.Context) ([]*WebauthnCredentials, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build find query: %w", err)
	}

	rows, err := d.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("execute find: %w", err)
	}
	defer rows.Close()

	var results []*WebauthnCredentials
	for rows.Next() {
		var result WebauthnCredentials
		err := rows.Scan(
			&result.ID,
			&result.UserID,
			&result.WebauthnID,
			&result.PublicKey,
			&result.AttestationType,
			&result.Transport,
			&result.Aaguid,
			&result.SignCount,
			&result.CloneWarning,
			&result.DeviceName,
			&result.CreatedAt,
			&result.LastUsedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("scan result: %w", err)
		}
		results = append(results, &result)
	}
	return results, rows.Err()
}

// First executes the query and returns the first matching record
func (d *webauthnCredentialsDo) First(ctx context.Context) (*WebauthnCredentials, error) {
	if !d.whereSet {
		d.builder = squirrel.Select().From(d.table).PlaceholderFormat(squirrel.Dollar)
		d.whereSet = true
	}
	if !d.selectSet {
		d.builder = d.builder.Columns(d.columns...)
	}
	d.builder = d.builder.Limit(1)

	query, args, err := d.builder.ToSql()
	if err != nil {
		return nil, fmt.Errorf("build first query: %w", err)
	}

	var result WebauthnCredentials
	err = d.db.QueryRowContext(ctx, query, args...).Scan(
		&result.ID,
		&result.UserID,
		&result.WebauthnID,
		&result.PublicKey,
		&result.AttestationType,
		&result.Transport,
		&result.Aaguid,
		&result.SignCount,
		&result.CloneWarning,
		&result.DeviceName,
		&result.CreatedAt,
		&result.LastUsedAt,
	)
	if err == sql.ErrNoRows {
		return nil, ErrRecordNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("execute first: %w", err)
	}
	return &result, nil
}

// Count returns the number of matching records
func (d *webauthnCredentialsDo) Count(ctx context.Context) (int64, error) {
	countBuilder := squirrel.Select("COUNT(*)").From(d.table).PlaceholderFormat(squirrel.Dollar)

	if d.whereSet {
		// Extract WHERE clauses from existing builder if any
		query, args, err := d.builder.ToSql()
		if err != nil {
			return 0, fmt.Errorf("build count query: %w", err)
		}
		// Parse WHERE clause from the query
		_ = query // TODO: extract WHERE clause properly
		_ = args
	}

	query, args, err := countBuilder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build count query: %w", err)
	}

	var count int64
	err = d.db.QueryRowContext(ctx, query, args...).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("execute count: %w", err)
	}
	return count, nil
}

// Update updates matching records with the given field-value pairs
func (d *webauthnCredentialsDo) Update(ctx context.Context, updates map[string]interface{}) (int64, error) {
	builder := squirrel.Update(d.table).PlaceholderFormat(squirrel.Dollar)

	for col, val := range updates {
		builder = builder.Set(col, val)
	}

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build update query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute update: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}

// Delete deletes matching records
func (d *webauthnCredentialsDo) Delete(ctx context.Context) (int64, error) {
	builder := squirrel.Delete(d.table).PlaceholderFormat(squirrel.Dollar)

	// TODO: Apply WHERE conditions from d.builder

	query, args, err := builder.ToSql()
	if err != nil {
		return 0, fmt.Errorf("build delete query: %w", err)
	}

	result, err := d.db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("execute delete: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("get rows affected: %w", err)
	}
	return affected, nil
}
