/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    DesktopLayout: typeof import('./src/components/layout/DesktopLayout.vue')['default']
    Dialog: typeof import('./src/components/ui/Dialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EmergencyActions: typeof import('./src/components/dashboard/EmergencyActions.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    Menu: typeof import('./src/components/ui/Menu.vue')['default']
    MobileLayout: typeof import('./src/components/layout/MobileLayout.vue')['default']
    MobileNav: typeof import('./src/components/layout/MobileNav.vue')['default']
    PullRefresh: typeof import('./src/components/ui/PullRefresh.vue')['default']
    ResponsiveLayout: typeof import('./src/components/layout/ResponsiveLayout.vue')['default']
    Ripple: typeof import('./src/components/ui/Ripple.vue')['default']
    RiskStatus: typeof import('./src/components/dashboard/RiskStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrategyOverview: typeof import('./src/components/dashboard/StrategyOverview.vue')['default']
    SystemHealth: typeof import('./src/components/dashboard/SystemHealth.vue')['default']
    Table: typeof import('./src/components/ui/Table.vue')['default']
    Tabs: typeof import('./src/components/ui/Tabs.vue')['default']
    Toast: typeof import('./src/components/ui/Toast.vue')['default']
    ToastContainer: typeof import('./src/components/ui/ToastContainer.vue')['default']
  }
}
